// Daily Dua dataset — 60 authentic duas from Quran and Sahih Hadith collections.
// Selection rotates by local calendar date so one new dua appears each day.

export interface DailyDua {
  id: string;
  arabic: string;
  transliteration: string;
  english: string;
  source: string;
  category: string;
}

/** Returns a zero-based day index that increments once per calendar day (local time). */
function duaDayIndex(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  return Math.floor((now.getTime() - start.getTime()) / 86_400_000);
}

export function getDailyDua(): DailyDua {
  // Offset from the Ayah/Hadith cycle so they don't repeat the same theme
  const idx = (duaDayIndex() + 17) % DUAS.length;
  return DUAS[idx];
}

// ─── Duas ─────────────────────────────────────────────────────────────────────

export const DUAS: DailyDua[] = [
  {
    id: "dua-001",
    arabic: "بِسْمِ اللَّهِ، اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا",
    transliteration: "Bismillāh, Allāhumma jannib-naš-shayṭāna wa jannibish-shayṭāna mā razaqtanā",
    english: "In the name of Allah. O Allah, keep us away from Satan, and keep Satan away from what You have bestowed upon us.",
    source: "Sahih Bukhari 3271",
    category: "Daily Life",
  },
  {
    id: "dua-002",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
    transliteration: "Alḥamdulillāhil-ladhī aṭ'amanā wa saqānā wa ja'alanā muslimīn",
    english: "All praise is for Allah who fed us and quenched our thirst and made us Muslims.",
    source: "Abu Dawud 3850, Tirmidhi 3458",
    category: "Eating",
  },
  {
    id: "dua-003",
    arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allāhumma bika aṣbaḥnā wa bika amsaynā wa bika naḥyā wa bika namūtu wa ilayk-an-nushūr",
    english: "O Allah, by You we enter the morning and by You we enter the evening. By You we live and by You we die, and to You is the resurrection.",
    source: "Tirmidhi 3391",
    category: "Morning",
  },
  {
    id: "dua-004",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
    transliteration: "Allāhumma bika amsaynā wa bika aṣbaḥnā wa bika naḥyā wa bika namūtu wa ilayk-al-maṣīr",
    english: "O Allah, by You we enter the evening and by You we enter the morning. By You we live, by You we die, and to You is the final return.",
    source: "Tirmidhi 3391",
    category: "Evening",
  },
  {
    id: "dua-005",
    arabic: "اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا",
    transliteration: "Allāhumma bismika amūtu wa aḥyā",
    english: "O Allah, in Your name I die and I live.",
    source: "Sahih Bukhari 6312",
    category: "Sleep",
  },
  {
    id: "dua-006",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alḥamdulillāhil-ladhī aḥyānā ba'da mā amātanā wa ilayhinn-nushūr",
    english: "All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.",
    source: "Sahih Bukhari 6312",
    category: "Waking",
  },
  {
    id: "dua-007",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbir-ḥamhumā kamā rabbayānī ṣaghīrā",
    english: "My Lord, have mercy upon them as they raised me when I was small.",
    source: "Quran 17:24",
    category: "Parents",
  },
  {
    id: "dua-008",
    arabic: "لَا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    transliteration: "Lā ilāha illā Anta subḥānaka innī kuntu minaẓ-ẓālimīn",
    english: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    source: "Quran 21:87 — Dua of Yunus ﷺ",
    category: "Forgiveness",
  },
  {
    id: "dua-009",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration: "Rabbanā ātinā fid-dunyā ḥasanatan wa fil-ākhirati ḥasanatan wa qinā 'adhāban-nār",
    english: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
    source: "Quran 2:201",
    category: "General",
  },
  {
    id: "dua-010",
    arabic: "اللَّهُمَّ أَنتَ رَبِّي لَا إِلَهَ إِلَّا أَنتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنتَ",
    transliteration: "Allāhumma Anta Rabbī lā ilāha illā Anta, khalaqtanī wa ana 'abduka, wa ana 'alā 'ahdika wa wa'dika mastata'tu. A'ūdhu bika min sharri mā ṣana'tu. Abū'u laka bini'matika 'alayya wa abū'u bidhanbī faghfir lī fa'innahū lā yaghfirudhdhunūba illā Ant",
    english: "O Allah, You are my Lord. There is no god but You. You created me and I am Your servant, and I hold to Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessings upon me and I confess my sins to You, so forgive me, for none forgives sins but You.",
    source: "Sahih Bukhari 6306 — Sayyid al-Istighfar",
    category: "Forgiveness",
  },
  {
    id: "dua-011",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillāhi walajnā wa bismillāhi kharajnā wa 'alalLāhi Rabbinā tawakkalnā",
    english: "In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we place our trust.",
    source: "Abu Dawud 5096",
    category: "Home",
  },
  {
    id: "dua-012",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلَجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Allāhumma innī as'aluka khayral-mawlaji wa khayral-makhraji, bismillāhi walajnā wa bismillāhi kharajnā wa 'alallāhi Rabbinā tawakkalnā",
    english: "O Allah, I ask You for the best of the entering and the best of the leaving. In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we rely.",
    source: "Abu Dawud 5096",
    category: "Home",
  },
  {
    id: "dua-013",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allāhummaf-taḥ lī abwāba raḥmatik",
    english: "O Allah, open for me the gates of Your mercy.",
    source: "Sahih Muslim 713 — upon entering the mosque",
    category: "Mosque",
  },
  {
    id: "dua-014",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "Allāhumma innī as'aluka min faḍlik",
    english: "O Allah, I ask You of Your bounty.",
    source: "Sahih Muslim 713 — upon leaving the mosque",
    category: "Mosque",
  },
  {
    id: "dua-015",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'ūdhu bikalimātillāhit-tāmmāti min sharri mā khalaq",
    english: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Sahih Muslim 2709",
    category: "Protection",
  },
  {
    id: "dua-016",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transliteration: "Rabbi zidnī 'ilmā",
    english: "My Lord, increase me in knowledge.",
    source: "Quran 20:114",
    category: "Knowledge",
  },
  {
    id: "dua-017",
    arabic: "رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
    transliteration: "Rabbi innī limā anzalta ilayya min khayrin faqīr",
    english: "My Lord, indeed I am in need of whatever good You would send down to me.",
    source: "Quran 28:24 — Dua of Musa ﷺ",
    category: "Provision",
  },
  {
    id: "dua-018",
    arabic: "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    transliteration: "Rabbish-raḥ lī ṣadrī wa yassir lī amrī",
    english: "My Lord, expand for me my chest and ease for me my task.",
    source: "Quran 20:25–26 — Dua of Musa ﷺ",
    category: "Ease",
  },
  {
    id: "dua-019",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً",
    transliteration: "Rabbanā lā tuzigh qulūbanā ba'da idh hadaytanā wa hab lanā mil-ladunka raḥmah",
    english: "Our Lord, let not our hearts deviate after You have guided us, and grant us from Yourself mercy.",
    source: "Quran 3:8",
    category: "Guidance",
  },
  {
    id: "dua-020",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    transliteration: "Allāhumma innī a'ūdhu bika minal-hammi wal-ḥazani, wal-'ajzi wal-kasali, wal-bukhli wal-jubni, wa ḍala'id-dayni wa ghalabatir-rijāl",
    english: "O Allah, I seek refuge in You from anxiety and grief, from weakness and laziness, from miserliness and cowardice, and from the burden of debt and the overpowering of men.",
    source: "Sahih Bukhari 2893",
    category: "Protection",
  },
  {
    id: "dua-021",
    arabic: "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا وَفِي لِسَانِي نُورًا وَفِي سَمْعِي نُورًا وَفِي بَصَرِي نُورًا",
    transliteration: "Allāhummaj-'al fī qalbī nūran wa fī lisānī nūran wa fī sam'ī nūran wa fī baṣarī nūrā",
    english: "O Allah, place light in my heart, light in my tongue, light in my hearing, and light in my sight.",
    source: "Sahih Bukhari 6316",
    category: "Light",
  },
  {
    id: "dua-022",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    transliteration: "Allāhumma innī as'alukal-'afwa wal-'āfiyata fid-dunyā wal-ākhirah",
    english: "O Allah, I ask You for pardon and well-being in this world and in the Hereafter.",
    source: "Sahih Ibn Majah 3871",
    category: "General",
  },
  {
    id: "dua-023",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata a'yunin waj-'alnā lil-muttaqīna imāmā",
    english: "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.",
    source: "Quran 25:74",
    category: "Family",
  },
  {
    id: "dua-024",
    arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
    transliteration: "Rabbij-'alnī muqīmaṣ-ṣalāti wa min dhurriyyatī, Rabbanā wa taqabbal du'ā'",
    english: "My Lord, make me an establisher of prayer, and from my descendants. Our Lord, and accept my supplication.",
    source: "Quran 14:40 — Dua of Ibrahim ﷺ",
    category: "Prayer",
  },
  {
    id: "dua-025",
    arabic: "اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ",
    transliteration: "Allāhumma raḥmataka arjū falā takilnī ilā nafsī ṭarfata 'aynin wa aṣliḥ lī sha'nī kullah",
    english: "O Allah, I hope for Your mercy; do not leave me to myself for even the blink of an eye, and rectify all of my affairs.",
    source: "Abu Dawud 5090",
    category: "Reliance",
  },
  {
    id: "dua-026",
    arabic: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "Ḥasbiyallāhu lā ilāha illā huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'aẓīm",
    english: "Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Mighty Throne.",
    source: "Quran 9:129",
    category: "Reliance",
  },
  {
    id: "dua-027",
    arabic: "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    transliteration: "Rabbanā-ghfir lanā dhunūbanā wa isrāfanā fī amrinā wa thabbit aqdāmanā wanṣurnā 'alal-qawmil-kāfirīn",
    english: "Our Lord, forgive us our sins and the excess in our affairs, make firm our feet, and give us victory over the disbelieving people.",
    source: "Quran 3:147",
    category: "Victory",
  },
  {
    id: "dua-028",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الثَّبَاتَ فِي الْأَمْرِ وَالْعَزِيمَةَ عَلَى الرُّشْدِ",
    transliteration: "Allāhumma innī as'alukat-thabāta fil-amri wal-'azīmata 'alar-rushd",
    english: "O Allah, I ask You for steadfastness in all matters and determination in following the right path.",
    source: "Tirmidhi 3407",
    category: "Steadfastness",
  },
  {
    id: "dua-029",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    transliteration: "Allāhumma 'āfinī fī badanī, Allāhumma 'āfinī fī sam'ī, Allāhumma 'āfinī fī baṣarī",
    english: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.",
    source: "Abu Dawud 5090",
    category: "Health",
  },
  {
    id: "dua-030",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ وَمِنْ قَلْبٍ لَا يَخْشَعُ وَمِنْ نَفْسٍ لَا تَشْبَعُ وَمِنْ دَعْوَةٍ لَا يُسْتَجَابُ لَهَا",
    transliteration: "Allāhumma innī a'ūdhu bika min 'ilmin lā yanfa', wa min qalbin lā yakhsha', wa min nafsin lā tashba', wa min da'watin lā yustajābu lahā",
    english: "O Allah, I seek refuge in You from knowledge that does not benefit, from a heart that does not fear Allah, from a soul that is not satisfied, and from a supplication that is not answered.",
    source: "Sahih Muslim 2722",
    category: "Knowledge",
  },
  {
    id: "dua-031",
    arabic: "مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ",
    transliteration: "Massaniyadh-dhurru wa Anta arḥamur-rāḥimīn",
    english: "Adversity has touched me, and You are the Most Merciful of the merciful.",
    source: "Quran 21:83 — Dua of Ayyub ﷺ",
    category: "Hardship",
  },
  {
    id: "dua-032",
    arabic: "رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي",
    transliteration: "Rabbi innī ẓalamtu nafsī faghfir lī",
    english: "My Lord, indeed I have wronged myself, so forgive me.",
    source: "Quran 28:16 — Dua of Musa ﷺ",
    category: "Forgiveness",
  },
  {
    id: "dua-033",
    arabic: "رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا",
    transliteration: "Rabbanā lā tu'ākhidhnā in nasīnā aw akhṭa'nā",
    english: "Our Lord, do not impose blame upon us if we have forgotten or erred.",
    source: "Quran 2:286",
    category: "Forgiveness",
  },
  {
    id: "dua-034",
    arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
    transliteration: "Rabbanā-ghfir lī wa liwālidayya wa lil-mu'minīna yawma yaqūmul-ḥisāb",
    english: "Our Lord, forgive me and my parents and the believers the Day when the account is established.",
    source: "Quran 14:41 — Dua of Ibrahim ﷺ",
    category: "Parents",
  },
  {
    id: "dua-035",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ",
    transliteration: "Allāhumma innī a'ūdhu bika minal-kufri wal-faqr",
    english: "O Allah, I seek refuge in You from disbelief and from poverty.",
    source: "Abu Dawud 1544",
    category: "Protection",
  },
  {
    id: "dua-036",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
    transliteration: "Yā muqallibal-qulūbi thabbit qalbī 'alā dīnik",
    english: "O Turner of hearts, make my heart firm upon Your religion.",
    source: "Tirmidhi 2140",
    category: "Steadfastness",
  },
  {
    id: "dua-037",
    arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنتَ تَجْعَلُ الْحَزَنَ إِذَا شِئْتَ سَهْلًا",
    transliteration: "Allāhumma lā sahla illā mā ja'altahu sahlā wa Anta taj'alul-ḥazna idhā shi'ta sahlā",
    english: "O Allah, there is no ease except what You make easy, and You make the difficult easy when You will.",
    source: "Ibn Hibban 974",
    category: "Ease",
  },
  {
    id: "dua-038",
    arabic: "رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
    transliteration: "Rabbanā ātinā mil-ladunka raḥmatan wa hayyi' lanā min amrinā rashadā",
    english: "Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.",
    source: "Quran 18:10 — Dua of the People of the Cave",
    category: "Guidance",
  },
  {
    id: "dua-039",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ أَشْهَدُ أَن لَّا إِلَهَ إِلَّا أَنتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
    transliteration: "Subḥānaka Allāhumma wa biḥamdika ashhadu an lā ilāha illā Anta astaghfiruka wa atūbu ilayk",
    english: "Glory be to You, O Allah, and praise. I bear witness that there is none worthy of worship except You. I seek Your forgiveness and I repent to You.",
    source: "Tirmidhi 3433 — Kaffaratul Majlis",
    category: "Dhikr",
  },
  {
    id: "dua-040",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transliteration: "Allāhummak-finī biḥalālika 'an ḥarāmika wa aghnī bifaḍlika 'amman siwāk",
    english: "O Allah, suffice me with what You have made lawful, keeping me from what You have made unlawful, and make me independent of all others besides You.",
    source: "Tirmidhi 3563",
    category: "Provision",
  },
  {
    id: "dua-041",
    arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ",
    transliteration: "Rabbi awzi'nī an ashkura ni'mataka-llatī an'amta 'alayya wa 'alā wālidayya",
    english: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents.",
    source: "Quran 27:19 — Dua of Sulayman ﷺ",
    category: "Gratitude",
  },
  {
    id: "dua-042",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Lā ḥawla wa lā quwwata illā billāh",
    english: "There is no power and no strength except with Allah.",
    source: "Sahih Bukhari 6384",
    category: "Dhikr",
  },
  {
    id: "dua-043",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    transliteration: "Allāhumma ṣalli 'alā Muḥammadin wa 'alā āli Muḥammad",
    english: "O Allah, send blessings upon Muhammad and upon the family of Muhammad.",
    source: "Sahih Bukhari 3370",
    category: "Salawat",
  },
  {
    id: "dua-044",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    transliteration: "Allāhumma innī as'alukal-hudā wat-tuqā wal-'afāfa wal-ghinā",
    english: "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.",
    source: "Sahih Muslim 2721",
    category: "General",
  },
  {
    id: "dua-045",
    arabic: "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Rabbanā taqabbal minnā innaka Antas-Samī'ul-'Alīm",
    english: "Our Lord, accept from us. Indeed, You are the Hearing, the Knowing.",
    source: "Quran 2:127 — Dua of Ibrahim and Ismail ﷺ",
    category: "Acceptance",
  },
  {
    id: "dua-046",
    arabic: "اللَّهُمَّ أَصْلِحْ لِي دِينِيَ الَّذِي هُوَ عِصْمَةُ أَمْرِي وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي",
    transliteration: "Allāhumma aṣliḥ lī dīniyal-ladhī huwa 'iṣmatu amrī, wa aṣliḥ lī dunyāyal-latī fīhā ma'āshī, wa aṣliḥ lī ākhiratī-llatī fīhā ma'ādī",
    english: "O Allah, set right my religious commitment, which is the safeguard of my affairs; set right my worldly affairs, wherein is my livelihood; and set right my Hereafter, to which is my return.",
    source: "Sahih Muslim 2720",
    category: "General",
  },
  {
    id: "dua-047",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    transliteration: "A'ūdhu billāhi minash-shayṭānir-rajīm",
    english: "I seek refuge in Allah from the accursed Satan.",
    source: "Quran 16:98",
    category: "Protection",
  },
  {
    id: "dua-048",
    arabic: "اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَعَافِنِي وَاهْدِنِي وَارْزُقْنِي",
    transliteration: "Allāhummagh-fir lī warḥamnī wa 'āfinī wahdinī warzuqnī",
    english: "O Allah, forgive me, have mercy on me, grant me well-being, guide me, and provide for me.",
    source: "Sahih Muslim 2697",
    category: "General",
  },
  {
    id: "dua-049",
    arabic: "رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ",
    transliteration: "Rabbi a'ūdhu bika min hamazātish-shayāṭīni wa a'ūdhu bika rabbi an yaḥḍurūn",
    english: "My Lord, I seek refuge in You from the incitements of the devils, and I seek refuge in You, my Lord, from their presence.",
    source: "Quran 23:97–98",
    category: "Protection",
  },
  {
    id: "dua-050",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ حُسْنَ الْخَاتِمَةِ",
    transliteration: "Allāhumma innī as'aluka ḥusnal-khātimah",
    english: "O Allah, I ask You for a good ending.",
    source: "Al-Mu'jam al-Awsat — Tabarani",
    category: "Ending",
  },
  {
    id: "dua-051",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allāhumma a'innī 'alā dhikrika wa shukrika wa ḥusni 'ibādatik",
    english: "O Allah, help me to remember You, to thank You, and to worship You in an excellent manner.",
    source: "Abu Dawud 1522",
    category: "Worship",
  },
  {
    id: "dua-052",
    arabic: "اللَّهُمَّ آتِنَا فِي الدُّنْيَا حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration: "Allāhumma ātinā fid-dunyā ḥasanatan wa qinā 'adhāban-nār",
    english: "O Allah, give us good in this world and save us from the punishment of the Fire.",
    source: "Sahih Bukhari 4522 — most recited dua by the Prophet ﷺ",
    category: "General",
  },
  {
    id: "dua-053",
    arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ",
    transliteration: "Rabbanā afrigh 'alaynā ṣabran wa tawaffanā muslimīn",
    english: "Our Lord, pour upon us patience and let us die as Muslims in submission to You.",
    source: "Quran 7:126",
    category: "Patience",
  },
  {
    id: "dua-054",
    arabic: "رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ الظَّالِمِينَ وَنَجِّنَا بِرَحْمَتِكَ مِنَ الْقَوْمِ الْكَافِرِينَ",
    transliteration: "Rabbanā lā taj'alnā fitnatal-lil-qawmiẓ-ẓālimīna wa najjinā biraḥmatika minal-qawmil-kāfirīn",
    english: "Our Lord, make us not a trial for the wrongdoing people, and save us by Your mercy from the disbelieving people.",
    source: "Quran 10:85–86 — Dua of Musa's followers",
    category: "Protection",
  },
  {
    id: "dua-055",
    arabic: "اللَّهُمَّ أَنتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ",
    transliteration: "Allāhumma Antas-ṣāḥibu fis-safari wal-khalīfatu fil-ahl",
    english: "O Allah, You are the Companion on the journey and the Guardian of the family.",
    source: "Sahih Muslim 1342",
    category: "Travel",
  },
  {
    id: "dua-056",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ مِنْ خَيْرِ هَذِهِ الْقَرْيَةِ وَخَيْرِ أَهْلِهَا وَنَعُوذُ بِكَ مِن شَرِّهَا",
    transliteration: "Allāhumma innā nas'aluka min khayri hādhihil-qaryati wa khayri ahlihā, wa na'ūdhu bika min sharrihā",
    english: "O Allah, we ask You for the good of this town and the good of its people, and we seek refuge in You from its evil.",
    source: "Abu Dawud 2599",
    category: "Travel",
  },
  {
    id: "dua-057",
    arabic: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    transliteration: "Rabbanā ẓalamnā anfusanā wa illam taghfir lanā wa tarḥamnā lanakūnanna minal-khāsirīn",
    english: "Our Lord, we have wronged ourselves. If You do not forgive us and have mercy upon us, we will surely be among the losers.",
    source: "Quran 7:23 — Dua of Adam and Hawwa ﷺ",
    category: "Forgiveness",
  },
  {
    id: "dua-058",
    arabic: "اللَّهُمَّ مُصَرِّفَ الْقُلُوبِ صَرِّفْ قُلُوبَنَا عَلَى طَاعَتِكَ",
    transliteration: "Allāhumma muṣarriful-qulūbi ṣarrif qulūbanā 'alā ṭā'atik",
    english: "O Allah, Controller of hearts, direct our hearts to Your obedience.",
    source: "Sahih Muslim 2654",
    category: "Steadfastness",
  },
  {
    id: "dua-059",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
    transliteration: "Allāhumma innī as'alukal-jannata wa a'ūdhu bika minan-nār",
    english: "O Allah, I ask You for Paradise and I seek refuge in You from the Fire.",
    source: "Abu Dawud 792",
    category: "Hereafter",
  },
  {
    id: "dua-060",
    arabic: "تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Tawakkaltu 'alallāhi lā ḥawla wa lā quwwata illā billāh",
    english: "I place my trust in Allah. There is no power and no strength except with Allah.",
    source: "Abu Dawud 5095",
    category: "Reliance",
  },
];
