/**
 * QAC Root Meanings
 *
 * Compact lookup table: Arabic root (QAC-normalized Unicode) → { en, ur }
 *
 * Key encoding matches the Quranic Arabic Corpus (qac-roots.json) exactly:
 *   • All alif variants (أ إ آ ٱ) are stored as plain ا
 *   • Alif maqsura (ى) is stored as ya (ي)
 *   • No diacritics / shadda / tatweel
 *
 * `lookupRootMeaning(root)` normalizes the input before lookup, so callers
 * can pass the raw QAC root string directly from qacEntry.r without any
 * pre-processing.
 */

export interface RootMeaning {
  /** Concise English meaning of the root */
  en: string;
  /** Urdu equivalent */
  ur?: string;
}

// ─── Normalization ──────────────────────────────────────────────────────────────
// Converts any Arabic alif variant + alif maqsura → canonical QAC form.
function normalize(root: string): string {
  return root
    // hamza-on-alif variants → plain alif
    .replace(/[\u0623\u0625\u0622\u0671]/g, "\u0627")
    // alif maqsura → ya
    .replace(/\u0649/g, "\u064A")
    // ta marbuta → ha
    .replace(/\u0629/g, "\u0647")
    // strip diacritics / tatweel
    .replace(/[\u064B-\u065F\u06D6-\u06DC\u06DF-\u06E4\u0640]/g, "");
}

// ─── Root table (keys pre-normalized to QAC encoding) ──────────────────────────
export const ROOT_MEANINGS: Record<string, RootMeaning> = {

  // ─── ا ─────────────────────────────────────────────────────────────────────
  "امن": { en: "security, faith, trust", ur: "امن، ایمان، اعتماد" },
  "اتي": { en: "to come, to bring", ur: "آنا، لانا" },
  "اخذ": { en: "to take, to seize", ur: "لینا، پکڑنا" },
  "اذن": { en: "permission, ear", ur: "اجازت، کان" },
  "ارض": { en: "earth, land, ground", ur: "زمین، سرزمین" },
  "اسف": { en: "sorrow, grief, regret", ur: "افسوس، غم" },
  "اصل": { en: "origin, root, principle", ur: "اصل، بنیاد" },
  "اكل": { en: "to eat, to consume", ur: "کھانا، کھا جانا" },
  "امر": { en: "command, affair, matter", ur: "حکم، معاملہ، امر" },
  "امل": { en: "hope, aspiration", ur: "امید، آرزو" },
  "اهل": { en: "family, people, worthy", ur: "اہل، خاندان" },
  "اوي": { en: "to shelter, to refuge", ur: "پناہ دینا، ٹھکانا" },
  "ابو": { en: "father, ancestor", ur: "باپ، آبا" },
  "اخو": { en: "brother", ur: "بھائی" },

  // ─── ب ─────────────────────────────────────────────────────────────────────
  "بدا": { en: "to begin, to start", ur: "شروع کرنا، آغاز" },
  "بدل": { en: "to change, to substitute", ur: "بدلنا، تبدیل کرنا" },
  "برا": { en: "to create, to be free of", ur: "پیدا کرنا، بری ہونا" },
  "برر": { en: "righteousness, piety, dutiful", ur: "نیکی، تقویٰ، فرماں برداری" },
  "بصر": { en: "sight, vision, insight", ur: "بصارت، نظر، بصیرت" },
  "بعث": { en: "to send, to raise up, to resurrect", ur: "بھیجنا، اٹھانا" },
  "بعد": { en: "after, distance, far", ur: "بعد، دوری" },
  "بقي": { en: "to remain, to last", ur: "باقی رہنا، بقا" },
  "بكي": { en: "to weep, to cry", ur: "رونا" },
  "بلغ": { en: "to reach, to convey, to mature", ur: "پہنچنا، پہنچانا" },
  "بني": { en: "to build, to construct; son", ur: "بنانا، بیٹا" },
  "بيت": { en: "house, home", ur: "گھر، خانہ" },
  "بين": { en: "between, clear, evident", ur: "درمیان، واضح، ظاہر" },
  "بشر": { en: "human being, glad tidings", ur: "انسان، بشارت" },
  "بلو": { en: "trial, to test, tribulation", ur: "آزمانا، بلا" },

  // ─── ت ─────────────────────────────────────────────────────────────────────
  "تبع": { en: "to follow, to pursue", ur: "پیروی کرنا، اتباع" },
  "توب": { en: "to repent, to turn back", ur: "توبہ کرنا، رجوع کرنا" },

  // ─── ث ─────────────────────────────────────────────────────────────────────
  "ثقل": { en: "weight, burden, heavy", ur: "بوجھ، بھاری" },
  "ثلث": { en: "three, third", ur: "تین، تہائی" },
  "ثمر": { en: "fruit, produce", ur: "پھل" },
  "ثمن": { en: "price, value", ur: "قیمت، مول" },

  // ─── ج ─────────────────────────────────────────────────────────────────────
  "جيا": { en: "to come, to arrive", ur: "آنا، تشریف لانا" },
  "جبر": { en: "to compel, to repair; might", ur: "مجبور کرنا، جبار" },
  "جحد": { en: "to deny, to reject", ur: "انکار کرنا" },
  "جزي": { en: "to recompense, to reward", ur: "جزا دینا، بدلہ دینا" },
  "جعل": { en: "to make, to place, to appoint", ur: "بنانا، مقرر کرنا" },
  "جهد": { en: "to strive, to struggle", ur: "کوشش کرنا، جہاد" },
  "جهل": { en: "ignorance, foolishness", ur: "جہالت، نادانی" },
  "جمع": { en: "to gather, to collect, to unite", ur: "جمع کرنا، اکٹھا کرنا" },
  "جنب": { en: "side, to avoid", ur: "پہلو، بچنا" },
  "جنن": { en: "garden, paradise; hidden; madness", ur: "باغ، جنت، پوشیدہ" },
  "جند": { en: "army, troops", ur: "فوج، لشکر" },

  // ─── ح ─────────────────────────────────────────────────────────────────────
  "حبط": { en: "to nullify, to make vain", ur: "اعمال ضائع کرنا" },
  "حبس": { en: "to confine, to hold back", ur: "قید کرنا، روکنا" },
  "حجج": { en: "argument, proof, pilgrimage", ur: "دلیل، حج، حجت" },
  "حدد": { en: "limits, boundaries", ur: "حد، سرحد" },
  "حذر": { en: "caution, to be wary", ur: "احتیاط، خبردار رہنا" },
  "حرم": { en: "forbidden, sacred, to prohibit", ur: "حرام، ممنوع، مقدس" },
  "حزن": { en: "grief, sadness", ur: "غم، حزن" },
  "حسب": { en: "to account, to reckon, to suffice", ur: "حساب کرنا، کافی ہونا" },
  "حسن": { en: "good, beautiful, excellent", ur: "اچھا، خوبصورت" },
  "حفظ": { en: "to guard, to protect, to memorize", ur: "حفاظت کرنا، یاد کرنا" },
  "حقق": { en: "truth, right, due; to verify", ur: "حق، سچ" },
  "حكم": { en: "wisdom, judgment, rule", ur: "حکمت، فیصلہ، حکم" },
  "حلل": { en: "lawful, permissible", ur: "حلال، جائز" },
  "حمد": { en: "praise, gratitude", ur: "حمد، تعریف، شکر" },
  "حمل": { en: "to carry, to bear a burden", ur: "اٹھانا، بوجھ اٹھانا" },
  "حيي": { en: "life, to live, to be alive", ur: "زندگی، جینا" },
  "حوت": { en: "whale, fish", ur: "مچھلی" },
  "حول": { en: "around, power, change", ur: "ارد گرد، طاقت، تبدیلی" },
  "حرب": { en: "war, conflict", ur: "جنگ، لڑائی" },
  "حبب": { en: "love, to love, beloved", ur: "محبت، پسند" },
  "حسد": { en: "envy, jealousy", ur: "حسد، جلن" },
  "حجب": { en: "veil, screen, to hide", ur: "پردہ، حجاب" },

  // ─── خ ─────────────────────────────────────────────────────────────────────
  "خبر": { en: "news, knowledge, to be aware", ur: "خبر، علم" },
  "خبث": { en: "evil, malicious, wicked", ur: "خباثت، برائی، ناپاک" },
  "خرج": { en: "to go out, to exit", ur: "نکلنا، خروج" },
  "خزي": { en: "disgrace, humiliation", ur: "رسوائی، ذلت" },
  "خشي": { en: "to fear, awe-inspiring reverence", ur: "ڈرنا، خشیت" },
  "خطا": { en: "error, mistake, sin", ur: "خطا، غلطی، گناہ" },
  "خطب": { en: "to address, important matter", ur: "خطبہ دینا، اہم معاملہ" },
  "خلص": { en: "pure, sincere, to save", ur: "خالص، مخلص" },
  "خلق": { en: "to create, character, nature", ur: "پیدا کرنا، خلق، اخلاق" },
  "خوف": { en: "fear, dread", ur: "خوف، ڈر" },
  "خير": { en: "good, goodness, better", ur: "خیر، بھلائی" },
  "خلف": { en: "behind, to succeed, successor", ur: "پیچھے، خلیفہ" },
  "خلد": { en: "eternity, to be immortal", ur: "ابدیت، ہمیشگی" },
  "خشع": { en: "humility, submission, reverence", ur: "خشوع، عاجزی" },
  "خصم": { en: "adversary, dispute", ur: "دشمن، جھگڑا" },
  "خوض": { en: "to wade into, to engage vainly", ur: "بیہودہ بات کرنا" },

  // ─── د ─────────────────────────────────────────────────────────────────────
  "دخل": { en: "to enter, to go in", ur: "داخل ہونا، گھسنا" },
  "درس": { en: "to study, to erase, to efface", ur: "پڑھنا، سیکھنا" },
  "دعو": { en: "to call, to invite, supplication", ur: "دعا، بلانا، پکارنا" },
  "دفع": { en: "to repel, to push away", ur: "دفع کرنا، روکنا" },
  "دنو": { en: "near, close, worldly", ur: "قریب، دنیا" },
  "دور": { en: "to revolve, rotation", ur: "گھومنا، دائرہ" },
  "دين": { en: "religion, faith, judgment, debt", ur: "دین، مذہب، قرض، جزا" },
  "درج": { en: "gradual, stages", ur: "درجہ، مرحلہ" },

  // ─── ذ ─────────────────────────────────────────────────────────────────────
  "ذكر": { en: "to remember, to mention, remembrance", ur: "یاد کرنا، ذکر، تذکرہ" },
  "ذنب": { en: "sin, crime, guilt", ur: "گناہ، جرم" },
  "ذهب": { en: "to go, to depart; gold", ur: "جانا، سونا" },
  "ذرر": { en: "offspring, to scatter, atom", ur: "ذریت، اولاد" },
  "ذوق": { en: "to taste, to experience", ur: "ذائقہ، چکھنا" },

  // ─── ر ─────────────────────────────────────────────────────────────────────
  "راي": { en: "to see, to observe, opinion", ur: "دیکھنا، رائے" },
  "ربب": { en: "lord, master, to nurture", ur: "رب، پالنہار، مالک" },
  "ربح": { en: "profit, gain", ur: "نفع، فائدہ" },
  "رجع": { en: "to return, to come back", ur: "واپس جانا، لوٹنا" },
  "رجو": { en: "to hope, to expect", ur: "امید کرنا، توقع" },
  "رحم": { en: "mercy, compassion, womb", ur: "رحم، مہربانی، شفقت" },
  "رزق": { en: "provision, sustenance, livelihood", ur: "رزق، روزی، سہارا" },
  "رسل": { en: "messenger, apostle, to send", ur: "رسول، پیغمبر، بھیجنا" },
  "رشد": { en: "right-mindedness, guidance, maturity", ur: "رشد، ہدایت، پختگی" },
  "رضو": { en: "to be pleased, consent, approval", ur: "راضی ہونا، خوشی" },
  "رعي": { en: "to tend, to guard, to observe", ur: "نگرانی کرنا، چرانا" },
  "رقب": { en: "to watch over, to observe", ur: "نگرانی کرنا، رقیب" },
  "رهب": { en: "fear, awe, to inspire dread", ur: "خوف، ہیبت، رہبانیت" },
  "ربط": { en: "to tie, to bind, to steady", ur: "باندھنا، ربط" },
  "رفع": { en: "to raise, to exalt, to elevate", ur: "اٹھانا، بلند کرنا" },
  "رتل": { en: "to recite slowly, to arrange", ur: "ترتیل، آہستہ پڑھنا" },
  "ركع": { en: "to bow, to kneel", ur: "رکوع، جھکنا" },
  "رهن": { en: "pledge, security, detained", ur: "رہن، گروی" },

  // ─── ز ─────────────────────────────────────────────────────────────────────
  "زكو": { en: "purification, growth, alms", ur: "پاکی، زکوۃ، بڑھنا" },
  "زيد": { en: "to increase, to add", ur: "زیادہ کرنا، بڑھانا" },
  "زود": { en: "provisions, to provide", ur: "زاد، سامان" },

  // ─── س ─────────────────────────────────────────────────────────────────────
  "سبح": { en: "to glorify, to swim, to travel", ur: "تسبیح کرنا، پاکی بیان کرنا" },
  "سبل": { en: "way, path, road", ur: "راستہ، سبیل" },
  "سجد": { en: "to prostrate, to bow down", ur: "سجدہ کرنا، جھکنا" },
  "سخر": { en: "to subjugate, to mock", ur: "مسخر کرنا، مذاق اڑانا" },
  "سرر": { en: "joy, happiness, secret", ur: "خوشی، مسرت، راز" },
  "سعي": { en: "to strive, to walk, to run", ur: "سعی کرنا، کوشش کرنا" },
  "سفه": { en: "foolishness, ignorance", ur: "بیوقوفی، سفاہت" },
  "سكن": { en: "to dwell, to rest, tranquility", ur: "رہنا، سکون، آرام" },
  "سلم": { en: "peace, submission, safety", ur: "سلامتی، اسلام، امن" },
  "سمع": { en: "to hear, listening", ur: "سننا، سمع" },
  "سوا": { en: "evil, harm, misfortune", ur: "برائی، برا، نقصان" },
  "سوي": { en: "to be equal, to make level", ur: "برابر کرنا، ہموار" },
  "سجن": { en: "prison, to imprison", ur: "جیل، قید" },
  "سفر": { en: "to travel, journey", ur: "سفر، سفر کرنا" },
  "سبق": { en: "to precede, to outrun", ur: "آگے بڑھنا، سبقت" },
  "سلط": { en: "authority, power, to dominate", ur: "سلطہ، اختیار" },
  "سال": { en: "to ask, to question, to beg", ur: "پوچھنا، مانگنا، سوال" },
  "صحب": { en: "companion, to accompany", ur: "ساتھی، صحبت" },
  "سجل": { en: "to register, scroll, record", ur: "درج کرنا، سجل" },
  "شكو": { en: "to complain, complaint", ur: "شکایت کرنا" },

  // ─── ش ─────────────────────────────────────────────────────────────────────
  "شفع": { en: "intercession, to intercede", ur: "شفاعت، سفارش" },
  "شكر": { en: "gratitude, thankfulness", ur: "شکر، شکریہ" },
  "شهد": { en: "to witness, to testify, martyr", ur: "گواہی دینا، شہید" },
  "شيا": { en: "thing, matter, something", ur: "چیز، شے" },
  "شرك": { en: "to associate, partnership, polytheism", ur: "شرک، شریک کرنا" },
  "شرع": { en: "law, to legislate, to begin", ur: "شریعت، قانون" },
  "شرب": { en: "to drink", ur: "پینا" },
  "شرح": { en: "to explain, to open, to expand", ur: "شرح کرنا، کھولنا" },
  "شيب": { en: "gray hair, old age", ur: "سفید بال، بڑھاپا" },

  // ─── ص ─────────────────────────────────────────────────────────────────────
  "صبر": { en: "patience, endurance, perseverance", ur: "صبر، برداشت" },
  "صدق": { en: "truth, truthfulness, sincerity", ur: "سچائی، صدق" },
  "صرط": { en: "path, road, way", ur: "راستہ، صراط" },
  "صلح": { en: "righteousness, goodness, reconciliation", ur: "صلح، درستگی، نیکی" },
  "صلو": { en: "prayer, blessings, to pray", ur: "نماز، درود، صلاۃ" },
  "صنع": { en: "to make, to work, craft", ur: "بنانا، کام کرنا، صنعت" },
  "صمد": { en: "eternal, absolute, besought by all", ur: "صمد، بے نیاز" },
  "صدر": { en: "chest, to issue from, heart", ur: "سینہ، صدر" },
  "صور": { en: "form, image, the trumpet", ur: "صورت، شکل، صور" },
  "صفح": { en: "to forgive, to turn away", ur: "معاف کرنا، صفح" },
  "صفو": { en: "pure, chosen, to purify", ur: "خالص، چنا ہوا" },

  // ─── ض ─────────────────────────────────────────────────────────────────────
  "ضرب": { en: "to strike, to travel, to coin", ur: "مارنا، مثال دینا" },
  "ضلل": { en: "to go astray, to mislead", ur: "گمراہ ہونا، ضلالت" },
  "ضرر": { en: "harm, injury, to harm", ur: "ضرر، نقصان" },
  "ضعف": { en: "weakness, to be weak", ur: "کمزوری، ضعف" },

  // ─── ط ─────────────────────────────────────────────────────────────────────
  "طغي": { en: "transgression, rebellion, excess", ur: "سرکشی، طغیان" },
  "طهر": { en: "purity, to be clean", ur: "پاکی، طہارت" },
  "طوع": { en: "willingness, to obey", ur: "اطاعت، خوشی سے ماننا" },
  "طلب": { en: "to seek, to demand, request", ur: "طلب، مانگنا" },
  "طبع": { en: "nature, to seal, to stamp", ur: "طبعیت، مہر لگانا" },
  "طول": { en: "length, to be long, bounty", ur: "لمبائی، طوالت، فضل" },

  // ─── ع ─────────────────────────────────────────────────────────────────────
  "عبد": { en: "servant, to worship, slavery", ur: "عبادت، بندہ، عبد" },
  "عذب": { en: "punishment, torment", ur: "عذاب، سزا" },
  "عرف": { en: "to know, to recognize", ur: "جاننا، پہچاننا، عرفان" },
  "عزز": { en: "might, power, honor", ur: "عزت، طاقت، غلبہ" },
  "عقل": { en: "reason, intellect, to comprehend", ur: "عقل، سمجھ" },
  "عقب": { en: "result, sequel, to follow behind", ur: "انجام، پیچھے آنا" },
  "علم": { en: "knowledge, to know, to learn", ur: "علم، جاننا" },
  "عمل": { en: "deed, action, work", ur: "عمل، کام، کرنا" },
  "عهد": { en: "covenant, promise, era", ur: "عہد، وعدہ، زمانہ" },
  "عود": { en: "to return, to revert", ur: "واپس آنا، لوٹنا" },
  "عون": { en: "help, assistance, support", ur: "مدد، اعانت" },
  "عمر": { en: "age, life, to inhabit", ur: "عمر، زندگی، آباد" },
  "عدل": { en: "justice, equity, to be just", ur: "عدل، انصاف" },
  "عدو": { en: "enemy, to transgress", ur: "دشمن، تجاوز" },
  "عرض": { en: "to offer, breadth, to display", ur: "پیش کرنا، چوڑائی" },
  "عفو": { en: "pardon, to forgive, to excuse", ur: "معافی، عفو" },
  "عجب": { en: "wonder, amazement", ur: "تعجب، حیرت" },
  "علو": { en: "height, to be high, exalted", ur: "بلندی، عالی" },
  "عصي": { en: "to disobey, rebellion", ur: "نافرمانی، معصیت" },

  // ─── غ ─────────────────────────────────────────────────────────────────────
  "غفر": { en: "forgiveness, to forgive", ur: "مغفرت، معاف کرنا" },
  "غيب": { en: "unseen, hidden, absent", ur: "غیب، پوشیدہ" },
  "غضب": { en: "anger, wrath", ur: "غضب، غصہ" },
  "غلب": { en: "to overcome, to prevail", ur: "غالب آنا، فتح" },
  "غني": { en: "richness, wealth, independence", ur: "غنا، امارت، بے نیازی" },

  // ─── ف ─────────────────────────────────────────────────────────────────────
  "فتح": { en: "to open, to conquer, victory", ur: "فتح، کھولنا" },
  "فجر": { en: "dawn, to burst forth", ur: "فجر، صبح، پھوٹنا" },
  "فرق": { en: "to separate, distinction", ur: "فرق، جدا کرنا" },
  "فسد": { en: "corruption, mischief, to corrupt", ur: "فساد، خرابی" },
  "فعل": { en: "to do, to act, deed", ur: "کرنا، فعل، عمل" },
  "فقه": { en: "understanding, jurisprudence", ur: "فہم، سمجھ، فقہ" },
  "فكر": { en: "to think, reflection", ur: "سوچنا، فکر" },
  "فوز": { en: "success, triumph, salvation", ur: "کامیابی، فلاح" },
  "فضل": { en: "grace, bounty, excellence", ur: "فضل، احسان، برتری" },
  "فلح": { en: "success, prosperity", ur: "فلاح، کامیابی" },
  "فتن": { en: "trial, tribulation, sedition", ur: "فتنہ، آزمائش" },
  "فرح": { en: "joy, happiness, to rejoice", ur: "خوشی، مسرت" },
  "فصل": { en: "to separate, chapter, to decide", ur: "فصل، الگ کرنا" },
  "فرض": { en: "obligation, to enjoin", ur: "فرض، لازم کرنا" },
  "فرد": { en: "individual, alone, unique", ur: "فرد، اکیلا" },

  // ─── ق ─────────────────────────────────────────────────────────────────────
  "قبل": { en: "before, to accept, to receive", ur: "پہلے، قبول کرنا" },
  "قتل": { en: "to kill, to slay", ur: "قتل کرنا، مارنا" },
  "قدر": { en: "power, measure, to decree", ur: "قدرت، اندازہ، تقدیر" },
  "قرا": { en: "to read, to recite, Quran", ur: "پڑھنا، تلاوت، قرآن" },
  "قرب": { en: "near, close, to draw near", ur: "قریب، نزدیک" },
  "قسم": { en: "oath, division, to swear", ur: "قسم، حصہ" },
  "قضي": { en: "to decree, to judge, to fulfill", ur: "فیصلہ کرنا، حکم دینا" },
  "قطع": { en: "to cut, to sever", ur: "کاٹنا، قطع کرنا" },
  "قلب": { en: "heart, to turn over", ur: "دل، قلب، پلٹنا" },
  "قنت": { en: "devout obedience, to be submissive", ur: "فرماں برداری، قنوت" },
  "قوم": { en: "people, nation; to stand upright", ur: "قوم، لوگ، کھڑا ہونا" },
  "قول": { en: "to say, speech, word", ur: "کہنا، قول" },
  "قرن": { en: "century, generation, to join", ur: "قرن، دور، جوڑنا" },
  "قسط": { en: "justice, equity, portion", ur: "انصاف، حصہ، قسط" },
  "قهر": { en: "to overpower, to dominate", ur: "قہر، غلبہ" },
  "قنع": { en: "contentment, to be satisfied", ur: "قناعت، سنتوش" },
  "قرع": { en: "to knock, calamity", ur: "کھٹکھٹانا، قارعہ" },
  "قسر": { en: "to force, to compel", ur: "زبردستی، مجبور کرنا" },
  "كيد": { en: "plot, scheme, cunning", ur: "چال، سازش" },

  // ─── ك ─────────────────────────────────────────────────────────────────────
  "كبر": { en: "greatness, to be great, arrogance", ur: "بڑائی، کبر، تکبر" },
  "كذب": { en: "to lie, falsehood, to deny", ur: "جھوٹ، کذب" },
  "كسب": { en: "to earn, to acquire", ur: "کمانا، حاصل کرنا" },
  "كشف": { en: "to uncover, to reveal", ur: "ظاہر کرنا، آشکار" },
  "كفر": { en: "to disbelieve, ingratitude, to cover", ur: "کفر، انکار، ناشکری" },
  "كلم": { en: "to speak, word, speech", ur: "کلام، بات، بولنا" },
  "كون": { en: "being, existence, to be", ur: "ہونا، وجود" },
  "كتب": { en: "to write, book, scripture", ur: "لکھنا، کتاب" },
  "كرم": { en: "generosity, nobility, honor", ur: "کرم، عزت، شرافت" },
  "كثر": { en: "abundance, many, much", ur: "کثرت، بہت" },
  "مكن": { en: "to establish, power, authority", ur: "قدرت، اقتدار" },

  // ─── ل ─────────────────────────────────────────────────────────────────────
  "لبث": { en: "to remain, to stay, to linger", ur: "ٹھہرنا، رہنا" },
  "لعن": { en: "curse, to curse", ur: "لعنت، لعنت کرنا" },
  "لقي": { en: "to meet, to encounter", ur: "ملنا، سامنا ہونا" },
  "لهو": { en: "amusement, play, distraction", ur: "کھیل، تماشا، لہو" },
  "لبس": { en: "to wear, to confuse", ur: "پہننا، التباس" },
  "لحق": { en: "to join, to catch up, to reach", ur: "ملنا، پہنچنا" },

  // ─── م ─────────────────────────────────────────────────────────────────────
  "مكر": { en: "scheming, plotting, deceit", ur: "مکر، چال، دھوکہ" },
  "ملك": { en: "king, dominion, to possess", ur: "بادشاہ، ملک، مالک" },
  "منع": { en: "to prevent, to withhold", ur: "روکنا، منع کرنا" },
  "موت": { en: "death, to die", ur: "موت، مرنا" },
  "مدد": { en: "to extend, to prolong, aid", ur: "مدد، بڑھانا" },
  "مثل": { en: "likeness, example, parable", ur: "مثال، مثل" },
  "مشي": { en: "to walk, to go", ur: "چلنا، جانا" },
  "محو": { en: "to erase, to obliterate", ur: "مٹانا، محو" },
  "منن": { en: "favor, to bestow, to cut", ur: "احسان، نعمت" },

  // ─── ن ─────────────────────────────────────────────────────────────────────
  "نبا": { en: "news, tidings, prophecy, prophet", ur: "خبر، نبی، پیغمبر" },
  "نجو": { en: "to save, to escape, salvation", ur: "نجات، بچنا" },
  "نذر": { en: "vow, to warn, to pledge", ur: "نذر، وعدہ، خبردار کرنا" },
  "نزل": { en: "to descend, to reveal", ur: "نازل ہونا، اترنا" },
  "نصر": { en: "help, victory, to support", ur: "مدد، نصرت، کامیابی" },
  "نظر": { en: "to look, to consider, sight", ur: "دیکھنا، نظر، غور کرنا" },
  "نعم": { en: "blessing, bounty, grace", ur: "نعمت، احسان" },
  "نفس": { en: "soul, self, life", ur: "نفس، روح، جان" },
  "نفع": { en: "benefit, advantage, profit", ur: "نفع، فائدہ" },
  "نهي": { en: "prohibition, to forbid, end", ur: "منع کرنا، نہی" },
  "نور": { en: "light, luminous", ur: "نور، روشنی" },
  "نفق": { en: "hypocrisy, tunnel, to spend", ur: "منافقت، خرچ کرنا" },
  "نسي": { en: "to forget, forgetfulness", ur: "بھولنا، نسیان" },
  "نشر": { en: "to spread, to resurrect", ur: "پھیلانا، نشر، قیامت" },
  "نكح": { en: "marriage, to marry", ur: "نکاح، شادی" },
  "نبذ": { en: "to cast away, to reject", ur: "پھینکنا، رد کرنا" },
  "نقم": { en: "vengeance, to punish", ur: "انتقام، سزا" },
  "نبت": { en: "to grow, to sprout", ur: "اگنا، نبات" },
  "نهر": { en: "river, to rebuke", ur: "دریا، نہر، ڈانٹنا" },

  // ─── ه ─────────────────────────────────────────────────────────────────────
  "هدي": { en: "guidance, to guide", ur: "ہدایت، راہ دکھانا" },
  "هلك": { en: "to perish, destruction", ur: "ہلاک ہونا، تباہی" },
  "هيا": { en: "awe, reverence, to fear", ur: "ہیبت، رعب، خوف" },
  "هجر": { en: "to abandon, to migrate", ur: "چھوڑنا، ہجرت" },

  // ─── و ─────────────────────────────────────────────────────────────────────
  "وجد": { en: "to find, to experience", ur: "پانا، محسوس کرنا" },
  "وجه": { en: "face, direction, purpose", ur: "چہرہ، وجہ، سمت" },
  "وحي": { en: "revelation, inspiration", ur: "وحی، الہام" },
  "وعد": { en: "promise, to promise, threat", ur: "وعدہ، پرامیس" },
  "وقي": { en: "to protect, to guard; God-consciousness", ur: "بچانا، تقویٰ" },
  "ولي": { en: "friend, guardian, protector", ur: "دوست، ولی، سرپرست" },
  "وهب": { en: "to give, to grant, gift", ur: "دینا، عطا کرنا" },
  "وصل": { en: "to reach, to connect, to arrive", ur: "پہنچنا، جوڑنا" },
  "وصف": { en: "to describe, attribute", ur: "بیان کرنا، وصف" },
  "وزن": { en: "weight, to weigh, balance", ur: "وزن، تولنا، ترازو" },
  "وسع": { en: "vast, spacious, to encompass", ur: "وسعت، کشادگی" },
  "وعظ": { en: "admonition, to admonish", ur: "وعظ، نصیحت" },
  "وجب": { en: "to be obligatory, to fall", ur: "واجب، لازم" },
  "وقف": { en: "to stand, to stop, endowment", ur: "رکنا، وقف" },

  // ─── ي ─────────────────────────────────────────────────────────────────────
  "يدي": { en: "hand, power, favor", ur: "ہاتھ، طاقت" },
  "يسر": { en: "ease, facilitation", ur: "آسانی، سہولت" },
  "يقن": { en: "certainty, conviction", ur: "یقین، قطعیت" },
  "يوم": { en: "day, time, era", ur: "دن، وقت" },

  // ─── Additional ─────────────────────────────────────────────────────────────
  "سمو": { en: "to be high, lofty, exalted", ur: "بلند، رفعت" },
  "اله": { en: "deity, god, to worship", ur: "الٰہ، معبود" },
  "روح": { en: "spirit, soul, revelation", ur: "روح، جان" },
  "ظلم": { en: "oppression, injustice, darkness", ur: "ظلم، ناانصافی، اندھیرا" },
  "ظهر": { en: "to appear, back, evident", ur: "ظاہر ہونا، پیٹھ" },
  "ظفر": { en: "victory, to succeed", ur: "ظفر، فتح" },
  "ظنن": { en: "assumption, conjecture, to think", ur: "گمان، خیال" },

  // ─── ا (expanded) ──────────────────────────────────────────────────────────
  "ابي": { en: "to refuse, to be unwilling", ur: "انکار کرنا، نہ ماننا" },
  "اخر": { en: "other, last, hereafter", ur: "دوسرا، آخری، آخرت" },
  "اذي": { en: "harm, hurt, annoyance", ur: "تکلیف، اذیت، ضرر" },
  "اسر": { en: "captivity, to bind, prisoner", ur: "قید، اسیر، باندھنا" },
  "افك": { en: "lie, slander, to turn away", ur: "جھوٹ، بہتان، الزام" },
  "ارث": { en: "inheritance, to inherit", ur: "وراثت، میراث" },
  "اوب": { en: "to return, to turn back", ur: "لوٹنا، واپس آنا" },
  "ابد": { en: "forever, eternity, eternal", ur: "ابد، ہمیشہ، دائمی" },
  "اسس": { en: "foundation, to establish", ur: "بنیاد، اساس" },
  "افق": { en: "horizon, limit", ur: "افق، کنارہ" },
  "امت": { en: "nation, community, period of time", ur: "امت، قوم، مدت" },
  "ابن": { en: "son, child", ur: "بیٹا، پسر" },
  "اجر": { en: "reward, wage, recompense", ur: "اجر، انعام، مزدوری" },
  "انس": { en: "to be familiar, human beings, to feel at ease", ur: "انس، مانوس ہونا، انسان" },
  "اسو": { en: "to follow example, consolation", ur: "اسوہ، تسلی" },
  "اود": { en: "to be burdensome, to curve", ur: "بوجھل ہونا" },

  // ─── ب (expanded) ──────────────────────────────────────────────────────────
  "بخل": { en: "miserliness, stinginess", ur: "بخل، کنجوسی" },
  "بذل": { en: "to spend freely, to give generously", ur: "خرچ کرنا، دینا" },
  "برج": { en: "tower, star, constellation", ur: "برج، ستارہ" },
  "بطل": { en: "false, vain, to be nullified", ur: "باطل، فضول" },
  "بغي": { en: "transgression, injustice, to exceed", ur: "بغاوت، سرکشی، بغی" },
  "بسط": { en: "to extend, to spread, to expand", ur: "پھیلانا، وسعت دینا" },
  "بكر": { en: "firstborn, early morning, virgin", ur: "پہلوٹھا، سویرا" },
  "بلد": { en: "city, land, country", ur: "شہر، ملک، علاقہ" },
  "برد": { en: "cold, hail, to cool", ur: "ٹھنڈ، اولے" },
  "بقر": { en: "cow, cattle", ur: "گائے، بقر" },
  "برق": { en: "lightning, to flash", ur: "بجلی، چمک" },
  "بسم": { en: "to name, in the name of", ur: "نام لینا، بسم" },
  "بتل": { en: "to devote entirely, to cut off", ur: "یکسو ہونا، کاٹنا" },
  "بوا": { en: "to settle, to lodge, to equal", ur: "برابر ہونا، اترنا" },
  "بطن": { en: "belly, interior, hidden", ur: "پیٹ، باطن، اندرونی" },
  "بعض": { en: "some, part, a portion", ur: "کچھ، بعض، حصہ" },
  "برهن": { en: "proof, clear evidence", ur: "دلیل، برہان" },
  "بكم": { en: "mute, dumb, speechless", ur: "گونگا، خاموش" },
  "بدو": { en: "to appear, to manifest, desert-dweller", ur: "ظاہر ہونا، بدوی" },
  "بسر": { en: "to frown, unripe dates", ur: "منہ بگاڑنا، کچی کھجور" },
  "بيع": { en: "selling, trade, to sell", ur: "بیچنا، تجارت، بیع" },
  "بلل": { en: "to moisten, to wet", ur: "تر کرنا، نم" },
  "بهج": { en: "joy, happiness, beautiful", ur: "خوشی، حسن، بہجت" },
  "بور": { en: "to perish, worthless", ur: "برباد ہونا، بے کار" },

  // ─── ت (expanded) ──────────────────────────────────────────────────────────
  "تبر": { en: "ruin, destruction, to destroy", ur: "تباہی، برباد کرنا" },
  "تبل": { en: "to follow consecutively", ur: "یکے بعد دیگرے آنا" },
  "ترب": { en: "dust, earth, poverty", ur: "مٹی، خاک، غربت" },
  "ترف": { en: "luxury, affluence, to live in ease", ur: "عیش، آسائش" },
  "تلي": { en: "to recite, to follow", ur: "تلاوت کرنا، پیچھے آنا" },
  "تمم": { en: "to complete, to perfect", ur: "مکمل کرنا، تکمیل" },
  "توي": { en: "to die, to perish", ur: "مرنا، ہلاک ہونا" },
  "تقو": { en: "God-consciousness, piety, fear of God", ur: "تقویٰ، پرہیزگاری" },
  "ترك": { en: "to leave, to abandon", ur: "چھوڑنا، ترک کرنا" },
  "تلو": { en: "following, to come after", ur: "پیچھے چلنا" },
  "تيه": { en: "wandering astray, lost", ur: "بھٹکنا، سرگردانی" },

  // ─── ث (expanded) ──────────────────────────────────────────────────────────
  "ثبت": { en: "to be firm, to establish, steadfast", ur: "ثابت رہنا، مضبوط" },
  "ثور": { en: "bull, to stir up, to rouse", ur: "بیل، ابھارنا" },
  "ثعبن": { en: "serpent, snake", ur: "سانپ، اژدہا" },
  "ثكل": { en: "bereavement, loss of child", ur: "بچے کا غم، صدمہ" },
  "ثلج": { en: "snow, coolness", ur: "برف، ٹھنڈک" },
  "ثوب": { en: "reward, garment, to return", ur: "ثواب، لباس، واپسی" },
  "ثرو": { en: "wealth, riches", ur: "دولت، ثروت" },
  "ثقف": { en: "to find, to overcome, to master", ur: "ملنا، قابو پانا" },

  // ─── ج (expanded) ──────────────────────────────────────────────────────────
  "جدل": { en: "to dispute, to argue", ur: "بحث کرنا، جدال" },
  "جري": { en: "to flow, to run, to happen", ur: "بہنا، دوڑنا، واقع ہونا" },
  "جلل": { en: "great, majestic, glorious", ur: "جلال، عظمت، بزرگی" },
  "جمل": { en: "camel, beauty, to make beautiful", ur: "اونٹ، خوبصورتی، جمال" },
  "جهز": { en: "to prepare, to equip", ur: "تیار کرنا، سامان دینا" },
  "جور": { en: "injustice, oppression, to deviate", ur: "ظلم، جور، انحراف" },
  "جلس": { en: "to sit, to dwell", ur: "بیٹھنا، ٹھہرنا" },
  "جذب": { en: "to attract, to pull", ur: "کھینچنا، اپنی طرف کھینچنا" },
  "جرم": { en: "crime, sin, to commit crime", ur: "جرم، گناہ" },
  "جدد": { en: "new, to renew", ur: "نیا، تجدید" },
  "جرح": { en: "wound, to wound, to criticize", ur: "زخم، جرح کرنا" },
  "جسد": { en: "body, physical form", ur: "جسم، بدن" },
  "جفو": { en: "to recede, to keep away", ur: "دور رہنا، الگ رہنا" },
  "جمد": { en: "to freeze, to be still", ur: "جمنا، ٹھہرنا" },
  "جوع": { en: "hunger, famine", ur: "بھوک، قحط" },
  "جسر": { en: "bridge, to be bold", ur: "پل، جسارت" },
  "جوز": { en: "to pass, middle, to allow", ur: "گزرنا، درمیان، جائز" },

  // ─── ح (expanded) ──────────────────────────────────────────────────────────
  "حجر": { en: "stone, to forbid, to restrain", ur: "پتھر، روکنا، حجر" },
  "حدث": { en: "to occur, new, event", ur: "واقع ہونا، نیا، حادثہ" },
  "حرث": { en: "to plough, harvest, tilth", ur: "کھیتی، حرث، ہل چلانا" },
  "حرص": { en: "eagerness, greed, to be anxious for", ur: "حرص، لالچ، بے تابی" },
  "حزب": { en: "party, group, division", ur: "گروہ، جماعت، حزب" },
  "حشر": { en: "gathering, resurrection, to assemble", ur: "حشر، جمع کرنا" },
  "حصن": { en: "fortress, to fortify, chastity", ur: "قلعہ، حصن، پاکدامنی" },
  "حضر": { en: "to be present, to attend", ur: "حاضر ہونا، موجود ہونا" },
  "حنف": { en: "inclination to truth, upright faith", ur: "حنیف، سیدھا دین" },
  "حسر": { en: "grief, regret, to be bare", ur: "حسرت، افسوس، ننگا" },
  "حصي": { en: "to count, pebbles, to enumerate", ur: "گننا، کنکری" },
  "حيض": { en: "menstruation", ur: "حیض، ماہواری" },
  "حوض": { en: "pool, basin, hawd", ur: "حوض، تالاب" },
  "حدق": { en: "garden, to surround, to encircle", ur: "باغ، گھیرنا" },
  "حلف": { en: "to swear, oath, alliance", ur: "قسم کھانا، حلف، معاہدہ" },
  "حور": { en: "to return, to be fair-complexioned; houri", ur: "حور، واپس آنا" },
  "حيو": { en: "to be alive, life, greeting", ur: "زندگی، سلام" },
  "حنن": { en: "compassion, affection, longing", ur: "رحم، محبت، لگاؤ" },
  "حيط": { en: "to surround, to encompass", ur: "گھیرنا، احاطہ" },
  "حرج": { en: "difficulty, tightness, sin", ur: "تنگی، مشکل، حرج" },
  "حوب": { en: "sin, wrongdoing", ur: "گناہ، خطا" },

  // ─── خ (expanded) ──────────────────────────────────────────────────────────
  "خبل": { en: "to corrupt, to render useless", ur: "خراب کرنا، بگاڑنا" },
  "خدع": { en: "to deceive, to cheat", ur: "دھوکہ دینا، فریب" },
  "خرط": { en: "to exaggerate, to impute", ur: "مبالغہ کرنا" },
  "خشب": { en: "wood, timber", ur: "لکڑی، تختہ" },
  "خضع": { en: "to be humble, to submit", ur: "فروتنی، جھکنا" },
  "خفف": { en: "lightness, to make light, to ease", ur: "ہلکا، تخفیف، کمی" },
  "خلو": { en: "to be empty, to be alone, to pass away", ur: "خالی ہونا، تنہا، گزر جانا" },
  "خمر": { en: "wine, to cover, to ferment", ur: "شراب، ڈھانپنا" },
  "خنس": { en: "to retreat, to slink back", ur: "پیچھے ہٹنا، چپکے سے نکلنا" },
  "خوت": { en: "kinship, fraternity", ur: "برادری، رشتہ داری" },
  "خيط": { en: "thread, line", ur: "دھاگہ، لکیر" },
  "ختم": { en: "to seal, to end, to stamp", ur: "مہر لگانا، ختم کرنا" },
  "خدم": { en: "servant, to serve", ur: "خادم، سیوا کرنا" },
  "خصص": { en: "to specify, to particularize", ur: "خاص کرنا، مخصوص" },
  "خنق": { en: "to strangle, throat, to choke", ur: "گلا گھونٹنا، گلا" },
  "خبو": { en: "to extinguish, to die down", ur: "بجھنا، ماند پڑنا" },
  "خصو": { en: "special, particular", ur: "خصوصی، مخصوص" },

  // ─── د (expanded) ──────────────────────────────────────────────────────────
  "دبر": { en: "back, to manage, to plan", ur: "پیٹھ، تدبیر، پیچھے" },
  "دحض": { en: "to refute, to slip", ur: "دلیل رد کرنا، پھسلنا" },
  "دحو": { en: "to spread out, to flatten", ur: "پھیلانا، بچھانا" },
  "درك": { en: "to reach, to catch, lowest depth", ur: "پہنچنا، پکڑنا، گہرائی" },
  "دلل": { en: "to point out, to guide, proof", ur: "دلالت، راہ دکھانا، دلیل" },
  "دمر": { en: "destruction, to destroy, ruin", ur: "تباہی، ہلاکت" },
  "دنس": { en: "impurity, filth, stain", ur: "ناپاکی، گندگی" },
  "دهي": { en: "calamity, misfortune", ur: "مصیبت، آفت" },
  "دهش": { en: "bewilderment, to be confused", ur: "حیرانگی، گھبراہٹ" },
  "ذعر": { en: "fright, terror", ur: "خوف، دہشت" },
  "دبب": { en: "to crawl, to creep", ur: "رینگنا" },
  "دفن": { en: "to bury, to conceal", ur: "دفن کرنا، چھپانا" },
  "دلو": { en: "bucket, to draw water", ur: "بالٹی، پانی نکالنا" },
  "دهر": { en: "time, ages, fate", ur: "زمانہ، دہر، وقت" },
  "دمع": { en: "tears, to weep", ur: "آنسو، رونا" },

  // ─── ذ (expanded) ──────────────────────────────────────────────────────────
  "ذرا": { en: "to scatter, to create, offspring", ur: "بکھیرنا، ذریت، پیدا کرنا" },
  "ذلل": { en: "humiliation, to abase, to make subservient", ur: "ذلت، رسوا کرنا" },
  "ذمم": { en: "blame, duty, responsibility", ur: "ذمہ، الزام، ذم" },
  "ذوي": { en: "family, kin, possessors of", ur: "اہل، رشتہ دار" },
  "ذيل": { en: "hem, tail, to trail", ur: "دامن، ذیل" },
  "ذرع": { en: "arm, measure, to intercede", ur: "ہاتھ، پیمائش، وسیلہ" },
  "ذكي": { en: "to slaughter, pure, smart", ur: "ذبح کرنا، پاک" },
  "ذلق": { en: "tip, to be sharp, eloquent", ur: "نوک، تیز، زبان دراز" },

  // ─── ر (expanded) ──────────────────────────────────────────────────────────
  "ربو": { en: "to increase, hill, interest (riba)", ur: "سود، بڑھنا، ٹیلہ" },
  "رتق": { en: "to join, to sew up", ur: "سینا، ملانا" },
  "رجس": { en: "filth, impurity, abomination", ur: "گندگی، نجاست، رجس" },
  "رحل": { en: "to travel, saddle, camel saddle", ur: "سفر کرنا، کوچ" },
  "ردد": { en: "to reject, to turn back, to repeat", ur: "رد کرنا، واپس کرنا" },
  "ردف": { en: "to follow, to come after", ur: "پیچھے آنا، ردیف" },
  "رسخ": { en: "firm, well-grounded, deeply rooted", ur: "راسخ، پختہ" },
  "رسو": { en: "to be anchored, to be firm", ur: "لنگر ڈالنا، قرار پانا" },
  "رعد": { en: "thunder", ur: "رعد، گرج" },
  "رغب": { en: "desire, longing, to be desirous", ur: "رغبت، خواہش" },
  "رفق": { en: "gentleness, kindness, companion", ur: "رفق، نرمی، رفیق" },
  "رقد": { en: "to sleep, to lie down", ur: "سونا، لیٹنا" },
  "رمي": { en: "to throw, to shoot, to cast", ur: "پھینکنا، رمی" },
  "رنج": { en: "sorrow, distress", ur: "غم، رنج" },
  "روي": { en: "to relate, to water, to satisfy thirst", ur: "روایت کرنا، سیراب" },
  "ريب": { en: "doubt, suspicion", ur: "شک، ریب، وسوسہ" },
  "رهق": { en: "to overwhelm, to cover, to be burdened", ur: "ڈھانپنا، بوجھ" },
  "رخو": { en: "softness, to be weak, gentle", ur: "نرمی، کمزوری" },
  "رفث": { en: "sexual relations, obscenity", ur: "رفث، مباشرت" },
  "رفض": { en: "to reject, to discard", ur: "رد کرنا، مسترد" },

  // ─── ز (expanded) ──────────────────────────────────────────────────────────
  "زجر": { en: "to rebuke, to repel, to restrain", ur: "ڈانٹنا، روکنا" },
  "زحم": { en: "crowding, to press, to push", ur: "بھیڑ، دھکیلنا" },
  "زخر": { en: "to surge, to overflow, to be filled", ur: "موجزن، لبریز" },
  "زرع": { en: "cultivation, crops, to sow", ur: "کاشت، فصل، بونا" },
  "زعم": { en: "to claim, to allege, to pretend", ur: "دعویٰ کرنا، زعم" },
  "زفر": { en: "to sigh, heavy breathing", ur: "ہانپنا، آہ بھرنا" },
  "زلل": { en: "to slip, to stumble, error", ur: "پھسلنا، لغزش، زلت" },
  "زمر": { en: "groups, flocks", ur: "گروہ، جتھا" },
  "زهد": { en: "asceticism, detachment, renunciation", ur: "زہد، دنیا سے بے رغبتی" },
  "زهق": { en: "to perish, to vanish, to expire", ur: "فنا ہونا، ختم ہونا" },
  "زور": { en: "false witness, to slant, to visit", ur: "جھوٹی گواہی، زور" },
  "زوج": { en: "spouse, pair, to marry", ur: "جوڑا، میاں بیوی، شادی" },
  "زين": { en: "adornment, beauty, to adorn", ur: "زینت، آرائش، سجانا" },
  "زيت": { en: "olive, oil", ur: "زیتون، تیل" },
  "زفف": { en: "to hasten, to march", ur: "تیز چلنا، دوڑنا" },
  "زلزل": { en: "earthquake, to shake", ur: "زلزلہ، ہلانا" },

  // ─── س (expanded) ──────────────────────────────────────────────────────────
  "سبا": { en: "Sheba, to capture, to take captive", ur: "سبا، اسیر کرنا" },
  "سبط": { en: "tribe, descendant, to be spacious", ur: "قبیلہ، نسل" },
  "سجر": { en: "to kindle, to fire up, to fill", ur: "سلگانا، بھرنا" },
  "سحب": { en: "to drag, to pull", ur: "گھسیٹنا، کھینچنا" },
  "سحر": { en: "magic, sorcery, dawn", ur: "جادو، سحر، صبح" },
  "سحق": { en: "to crush, to grind, far away", ur: "کچلنا، دور" },
  "سدد": { en: "to direct, right, straight", ur: "سیدھا، درست" },
  "سرع": { en: "to hasten, speed, quick", ur: "جلدی کرنا، تیز" },
  "سطر": { en: "line, to write, row", ur: "سطر، لکھنا" },
  "سطو": { en: "to attack, to seize, to overpower", ur: "حملہ کرنا، قابو کرنا" },
  "سفك": { en: "to shed blood, to pour", ur: "خون بہانا، بہانا" },
  "سقي": { en: "to give water, to water", ur: "پانی پلانا، سقی" },
  "سكر": { en: "intoxication, to be drunk", ur: "نشہ، مستی" },
  "سلخ": { en: "to strip off, to peel", ur: "چھیلنا، کھال اتارنا" },
  "سمم": { en: "poison, to poison", ur: "زہر، سم" },
  "سند": { en: "support, authority, to lean on", ur: "سند، سہارا" },
  "سهل": { en: "easy, to facilitate, plain", ur: "آسان، سہل" },
  "سهم": { en: "arrow, share, lot", ur: "تیر، حصہ، قرعہ" },
  "سهو": { en: "forgetfulness, inattention", ur: "بھول، غفلت، سہو" },
  "سوق": { en: "market, to drive, to urge", ur: "بازار، ہانکنا، سوق" },
  "سير": { en: "to travel, journey, conduct", ur: "سیر، سفر، چال" },
  "سنة": { en: "year, practice, established way", ur: "سال، سنت، طریقہ" },
  "صنو": { en: "equal, twin", ur: "مثل، جوڑا" },
  "سكت": { en: "to be silent, to calm down", ur: "خاموش ہونا، چپ" },
  "سمد": { en: "to be upright, to grieve", ur: "سمود، سیدھا" },

  // ─── ش (expanded) ──────────────────────────────────────────────────────────
  "شجر": { en: "tree, quarrel, to dispute", ur: "درخت، جھگڑا" },
  "شحح": { en: "miserliness, greed, to be stingy", ur: "بخل، لالچ" },
  "شدد": { en: "to be strong, to tie, to intensify", ur: "مضبوط کرنا، باندھنا، شدت" },
  "شذو": { en: "fragrance, pleasant smell", ur: "خوشبو" },
  "شرق": { en: "east, to rise (sun), to radiate", ur: "مشرق، طلوع" },
  "شطط": { en: "extremism, to go far, excess", ur: "زیادتی، غلو" },
  "شعر": { en: "to know, to feel, to perceive; poetry", ur: "شعور، احساس، شعر" },
  "شغل": { en: "preoccupation, to busy, distraction", ur: "مشغولیت، کام" },
  "شفق": { en: "twilight, compassion, concern", ur: "شفق، مغرب کی سرخی" },
  "شقق": { en: "difficulty, to split, to crack", ur: "مشقت، پھاڑنا، شق" },
  "شمل": { en: "to encompass, north wind, left", ur: "شامل کرنا، شمال" },
  "شنا": { en: "to hate, to abhor", ur: "نفرت کرنا، کراہت" },
  "شور": { en: "consultation, honey", ur: "مشورہ، شہد" },
  "شيخ": { en: "old man, elder, chief", ur: "بوڑھا، شیخ، سردار" },
  "شوي": { en: "to roast, to grill", ur: "بھوننا، پکانا" },
  "شعث": { en: "disheveled, scattered", ur: "بکھرا ہوا، پریشان" },
  "شمس": { en: "sun", ur: "سورج، شمس" },
  "شقا": { en: "misery, unhappiness, to be wretched", ur: "بدبختی، شقاوت" },
  "شبه": { en: "resemblance, doubt, likeness", ur: "مشابہت، شک، شبہ" },

  // ─── ص (expanded) ──────────────────────────────────────────────────────────
  "صعد": { en: "to ascend, to climb", ur: "چڑھنا، اوپر جانا" },
  "صغر": { en: "small, little, to be humiliated", ur: "چھوٹا، ذلیل" },
  "صفف": { en: "to arrange in rows, rank", ur: "صف، قطار" },
  "صفق": { en: "to strike, to clap", ur: "تالی بجانا، مارنا" },
  "صلب": { en: "backbone, crucifixion, hardness", ur: "ریڑھ کی ہڈی، سولی" },
  "صمت": { en: "silence, to be silent", ur: "خاموشی، صمت" },
  "صنم": { en: "idol, image", ur: "بت، صنم" },
  "صهر": { en: "in-laws, to melt", ur: "سسرال، پگھلانا" },
  "صوم": { en: "fasting, to fast", ur: "روزہ، صوم" },
  "صيد": { en: "hunting, game, to hunt", ur: "شکار" },
  "صبو": { en: "to incline, to lean", ur: "جھکنا، مائل ہونا" },
  "صرف": { en: "to turn away, to spend, change", ur: "پھیرنا، خرچ کرنا، صرف" },
  "صعق": { en: "thunderbolt, to be struck dead", ur: "بجلی، صاعقہ" },
  "صوت": { en: "voice, sound", ur: "آواز، صوت" },
  "صلد": { en: "bare, hard rock", ur: "چکنا پتھر، سخت" },
  "صخر": { en: "rock, stone", ur: "چٹان، پتھر" },

  // ─── ض (expanded) ──────────────────────────────────────────────────────────
  "ضجع": { en: "to lie down, to recline", ur: "لیٹنا، سونا" },
  "ضحك": { en: "to laugh, laughter", ur: "ہنسنا، ہنسی" },
  "ضحو": { en: "forenoon, to appear", ur: "چاشت، صبح" },
  "ضرع": { en: "to humble oneself, to supplicate", ur: "عاجزی کرنا، التجا" },
  "ضيف": { en: "guest, to host", ur: "مہمان، مہمان نوازی" },
  "ضيق": { en: "narrowness, distress", ur: "تنگی، پریشانی" },
  "ضغث": { en: "bundle of grass, confused dream", ur: "گھاس کا گٹھا، خواب" },
  "ضير": { en: "harm, to harm", ur: "نقصان، ضرر" },
  "ضرو": { en: "to necessitate, to force", ur: "مجبور کرنا، ضروری" },
  "ضنك": { en: "straitness, misery", ur: "تنگی، سختی" },

  // ─── ط (expanded) ──────────────────────────────────────────────────────────
  "طبق": { en: "layer, level, to be in accordance", ur: "طبق، پرت، موافق" },
  "طرح": { en: "to throw, to cast away", ur: "پھینکنا، دور کرنا" },
  "طرد": { en: "to expel, to drive away", ur: "نکالنا، بھگانا" },
  "طرف": { en: "end, side, glance", ur: "کنارہ، طرف، نظر" },
  "طوف": { en: "to circumambulate, to go around", ur: "طواف کرنا، گھومنا" },
  "طيب": { en: "good, pure, pleasant", ur: "طیب، پاک، اچھا" },
  "طمع": { en: "greed, covetousness, to desire", ur: "طمع، لالچ" },
  "طمس": { en: "to obliterate, to efface", ur: "مٹانا، محو کرنا" },
  "طور": { en: "Mount Tur, manner, beyond measure", ur: "طور، پہاڑ، حد سے" },
  "طيف": { en: "spectre, phantom, visiting dream", ur: "طیف، خیال" },
  "طوي": { en: "to fold, to roll up", ur: "لپیٹنا، موڑنا" },

  // ─── ع (expanded) ──────────────────────────────────────────────────────────
  "عبر": { en: "to cross over, to express, lesson", ur: "عبرت، سبق، پار ہونا" },
  "عتو": { en: "arrogance, to be insolent", ur: "سرکشی، گستاخی، عتو" },
  "عجل": { en: "haste, calf, to be hasty", ur: "جلدی، بچھڑا، عجلت" },
  "عدد": { en: "number, to count", ur: "عدد، شمار کرنا" },
  "عذر": { en: "excuse, to excuse, to warn", ur: "معذرت، عذر، عذر کرنا" },
  "عرش": { en: "throne, pavilion, trellis", ur: "عرش، تخت" },
  "عرو": { en: "handhold, to take hold of", ur: "دستہ، سہارا" },
  "عصب": { en: "nerve, group, to bind", ur: "عصبیت، رگ، گروہ" },
  "عصر": { en: "time, afternoon, to press", ur: "عصر، دور، نچوڑنا" },
  "عطف": { en: "compassion, to turn to, to bend", ur: "عطف، رحم، مڑنا" },
  "عظم": { en: "bone, greatness, to be great", ur: "ہڈی، عظمت، بڑا" },
  "عقد": { en: "contract, knot, to tie", ur: "گرہ، عقد، معاہدہ" },
  "علق": { en: "to cling, blood-clot, to attach", ur: "چمٹنا، علقہ، خون کا لوتھڑا" },
  "عمد": { en: "pillar, intentional, to intend", ur: "ستون، ارادہ، قصداً" },
  "عنق": { en: "neck, group", ur: "گردن، گروہ" },
  "عند": { en: "at, near, with, in the presence of", ur: "پاس، عند، نزدیک" },
  "عهن": { en: "wool, multi-colored", ur: "اون، رنگین" },
  "عيل": { en: "family dependents, poor", ur: "بال بچے، غریب" },
  "عين": { en: "eye, spring, essence", ur: "آنکھ، چشمہ، عین" },
  "عبث": { en: "vain, purposeless, to play", ur: "بے مقصد، کھیل، عبث" },
  "عكف": { en: "to devote oneself, to seclude", ur: "اعتکاف، خلوت" },
  "عذل": { en: "to blame, to reproach", ur: "الزام، ملامت" },
  "عسر": { en: "hardship, difficulty", ur: "مشکل، تنگی، عسر" },
  "عتق": { en: "freedom, ancient, to free", ur: "آزادی، آزاد کرنا" },
  "عرج": { en: "to ascend, to be lame", ur: "چڑھنا، معراج" },

  // ─── غ (expanded) ──────────────────────────────────────────────────────────
  "غدر": { en: "treachery, betrayal", ur: "غداری، دھوکہ" },
  "غرب": { en: "west, to set (sun), to be absent", ur: "مغرب، غروب، غریب" },
  "غرر": { en: "deception, risk, to deceive", ur: "دھوکہ، خطرہ، غرر" },
  "غرق": { en: "to drown, to be submerged", ur: "ڈوبنا، غرق" },
  "غسل": { en: "to wash, to bathe", ur: "غسل، دھونا" },
  "غشي": { en: "to cover, to overwhelm, to faint", ur: "ڈھانپنا، غشی، بے ہوشی" },
  "غفل": { en: "heedlessness, to be negligent", ur: "غفلت، بے توجہی" },
  "غلل": { en: "treachery, chains, burning thirst", ur: "غل، زنجیر، پیاس" },
  "غلو": { en: "to go to extremes, exaggeration", ur: "غلو، حد سے بڑھنا" },
  "غمر": { en: "to submerge, vast quantity, abundance", ur: "ڈوبنا، بہت زیادہ" },
  "غوث": { en: "help, to seek help, relief", ur: "فریاد، مدد" },
  "غول": { en: "to deceive, to harm", ur: "دھوکہ، ضرر" },
  "غيظ": { en: "rage, fury, extreme anger", ur: "غیظ، شدید غصہ" },
  "غسق": { en: "darkness of night", ur: "رات کا اندھیرا" },
  "غثو": { en: "scum, rubbish, foam", ur: "کوڑا، جھاگ" },

  // ─── ف (expanded) ──────────────────────────────────────────────────────────
  "فتق": { en: "to split, to open", ur: "پھاڑنا، کھولنا" },
  "فجو": { en: "vast space, open area", ur: "کشادہ جگہ، فجوہ" },
  "فرر": { en: "to flee, to escape", ur: "بھاگنا، فرار" },
  "فرط": { en: "to go ahead, excess, to neglect", ur: "آگے جانا، زیادتی" },
  "فسق": { en: "disobedience, transgression, immorality", ur: "فسق، گناہ، بدکاری" },
  "فشل": { en: "to fail, to weaken, cowardice", ur: "ناکامی، کمزوری" },
  "فقر": { en: "poverty, neediness", ur: "فقر، غریبی، محتاجی" },
  "فلق": { en: "daybreak, to split, cleave", ur: "صبح، پھاڑنا، فلق" },
  "فنن": { en: "branch, bough", ur: "شاخ، ٹہنی" },
  "فوق": { en: "above, over, beyond", ur: "اوپر، بالاتر" },
  "فيض": { en: "to overflow, bounty, flowing", ur: "فیضان، بہنا، نعمت" },
  "فحش": { en: "obscenity, lewdness, immorality", ur: "فحش، بے حیائی" },
  "فزع": { en: "fright, to be frightened", ur: "ڈر، گھبراہٹ، فزع" },
  "فلس": { en: "to become bankrupt, scale (of fish)", ur: "دیوالیہ، چھلکا" },
  "فور": { en: "boiling, at once, immediately", ur: "ابالنا، فوری" },

  // ─── ق (expanded) ──────────────────────────────────────────────────────────
  "قبض": { en: "to grasp, to withhold, death", ur: "پکڑنا، روکنا، قبضہ" },
  "قتت": { en: "to spy, tale-bearing", ur: "جاسوسی، چغلی" },
  "قحط": { en: "drought, famine", ur: "قحط، خشک سالی" },
  "قدم": { en: "foot, to go before, to offer", ur: "قدم، پیش کرنا، آگے" },
  "قذف": { en: "to cast, to throw, to accuse", ur: "پھینکنا، الزام، قذف" },
  "قسو": { en: "hardness of heart, harshness", ur: "قساوت، سختی" },
  "قطر": { en: "to drip, pitch, tar", ur: "ٹپکنا، قطرہ، رال" },
  "قعد": { en: "to sit, to remain behind", ur: "بیٹھنا، پیچھے رہنا" },
  "قلد": { en: "to imitate, to put on, necklace", ur: "نقل کرنا، ہار" },
  "قلق": { en: "anxiety, restlessness", ur: "بے چینی، قلق" },
  "قلي": { en: "to fry, to dislike", ur: "تلنا، ناپسند" },
  "قمر": { en: "moon", ur: "چاند، قمر" },
  "قنط": { en: "despair, hopelessness", ur: "مایوسی، قنوط" },
  "قوي": { en: "strength, power, ability", ur: "قوت، طاقت" },
  "قيم": { en: "upright, straight, valuable, to stand", ur: "قیم، سیدھا، قائم" },
  "قصص": { en: "story, narrative, to follow", ur: "قصہ، کہانی" },
  "قيد": { en: "shackle, restriction", ur: "بیڑی، پابندی" },
  "قصد": { en: "intention, to intend, moderate", ur: "قصد، ارادہ، میانہ" },
  "قبر": { en: "grave, tomb", ur: "قبر، مزار" },
  "قيل": { en: "midday nap, to say", ur: "دوپہر کی نیند، کہنا" },

  // ─── ك (expanded) ──────────────────────────────────────────────────────────
  "كدح": { en: "to toil, to strive", ur: "محنت کرنا، کوشش" },
  "كرب": { en: "distress, anguish, calamity", ur: "کرب، تکلیف، پریشانی" },
  "كره": { en: "dislike, coercion, against will", ur: "کراہت، نفرت، زبردستی" },
  "كسر": { en: "to break, to fracture", ur: "توڑنا، کسر" },
  "كظم": { en: "to suppress anger, to swallow", ur: "غصہ پینا، روکنا" },
  "كفل": { en: "to guarantee, to take charge", ur: "کفالت، ضمانت" },
  "كمل": { en: "to be complete, perfect", ur: "مکمل، کامل" },
  "كنز": { en: "treasure, to hoard", ur: "خزانہ، جمع کرنا" },
  "كهف": { en: "cave, refuge", ur: "غار، پناہ" },
  "كيل": { en: "measurement, to measure", ur: "ناپنا، پیمائش" },
  "كنس": { en: "to sweep, planets, to hide", ur: "کنس، چھپنا" },
  "كرر": { en: "to repeat, to return", ur: "دہرانا، واپس آنا" },
  "كحل": { en: "kohl, eyeliner, to apply kohl", ur: "سرمہ، کحل" },
  "كفأ": { en: "equivalent, equal, to be equal", ur: "برابر، ہم پلہ" },

  // ─── ل (expanded) ──────────────────────────────────────────────────────────
  "لجج": { en: "to persist, sea depth, obstinacy", ur: "ہٹ، اصرار، سمندر" },
  "لحم": { en: "flesh, meat", ur: "گوشت، لحم" },
  "لدد": { en: "to quarrel, most contentious", ur: "جھگڑالو، الد" },
  "لدن": { en: "from, at, in the presence of", ur: "پاس سے، لدن" },
  "لظي": { en: "blazing fire, flame", ur: "لظیٰ، شعلہ، آگ" },
  "لعب": { en: "to play, game, sport", ur: "کھیلنا، کھیل" },
  "لقط": { en: "to pick up, to find", ur: "اٹھانا، پانا" },
  "لوذ": { en: "to seek refuge, to flee to", ur: "پناہ لینا" },
  "لين": { en: "softness, gentleness", ur: "نرمی، لین" },
  "لمز": { en: "to find fault, to criticize", ur: "عیب نکالنا، ملامت" },
  "لوي": { en: "to twist, to turn away", ur: "موڑنا، پیچ" },
  "لوم": { en: "blame, to blame", ur: "ملامت، لوم" },
  "لمس": { en: "to touch, to feel", ur: "چھونا، لمس" },
  "لهب": { en: "flame, blaze", ur: "لہب، شعلہ" },
  "لبب": { en: "heart, intellect, mind", ur: "دل، عقل، لب" },
  "لسن": { en: "tongue, language", ur: "زبان، لسان" },
  "لقن": { en: "to prompt, to receive, to teach", ur: "یاد دلانا، سمجھانا" },

  // ─── م (expanded) ──────────────────────────────────────────────────────────
  "ماي": { en: "water", ur: "پانی، ماء" },
  "مرج": { en: "to mix, to confuse, meadow", ur: "ملانا، مرج، گھاس" },
  "مرر": { en: "to pass by, bitterness", ur: "گزرنا، کڑواہٹ" },
  "مسح": { en: "to wipe, to stroke, to anoint", ur: "مسح، پونچھنا" },
  "مسس": { en: "to touch, to afflict", ur: "چھونا، لگنا" },
  "مكث": { en: "to remain, to stay, to tarry", ur: "ٹھہرنا، رکنا" },
  "ملل": { en: "weariness, to be bored", ur: "اکتاہٹ، ملل" },
  "منو": { en: "death, time, to test", ur: "موت، منیٰ، آزمانا" },
  "موج": { en: "wave, to surge", ur: "لہر، موج" },
  "مهد": { en: "cradle, to prepare, to spread", ur: "جھولا، مہد، بچھانا" },
  "مهل": { en: "respite, slow, molten brass", ur: "مہلت، آہستہ، دھات" },
  "ميز": { en: "to distinguish, to separate", ur: "تمیز، الگ کرنا" },
  "مشج": { en: "mixed, diverse, mingled", ur: "ملا ہوا، امشاج" },
  "محص": { en: "to purify, to test", ur: "پاک کرنا، آزمانا" },
  "مهن": { en: "to be humble, to honor", ur: "خدمت، عزت" },
  "مزج": { en: "to mix, to blend", ur: "ملانا، مزج" },
  "مند": { en: "gift, to endow", ur: "منت، تحفہ" },
  "ميل": { en: "inclination, to incline", ur: "میلان، جھکاؤ" },
  "متع": { en: "to give enjoyment, goods", ur: "متاع، فائدہ، سامان" },

  // ─── ن (expanded) ──────────────────────────────────────────────────────────
  "نثر": { en: "to scatter, to disperse", ur: "بکھیرنا، منتشر کرنا" },
  "نجم": { en: "star, to appear", ur: "ستارہ، نجم" },
  "نجس": { en: "impurity, to be impure", ur: "نجاست، ناپاک" },
  "نحل": { en: "bees, to give generously", ur: "شہد کی مکھی، نحل" },
  "نحو": { en: "towards, grammar, slaughter", ur: "طرف، نحو" },
  "ندم": { en: "regret, remorse", ur: "پشیمانی، ندامت" },
  "ندو": { en: "council, to call, to summon", ur: "مجلس، بلانا" },
  "نذل": { en: "to be lowly, base, contemptible", ur: "ذلیل، پست، نذل" },
  "نرع": { en: "to pull out, restlessness", ur: "کھینچنا، بے چینی" },
  "نزع": { en: "to pull out, to dispute, strife", ur: "کھینچنا، جھگڑا" },
  "نسب": { en: "lineage, kinship, descent", ur: "نسب، خاندان، رشتہ" },
  "نسج": { en: "to weave", ur: "بننا، بنائی" },
  "نسخ": { en: "to abrogate, to copy, to transcribe", ur: "نسخ، منسوخ کرنا" },
  "نشز": { en: "to rise, disobedience (of wife)", ur: "نشوز، سرکشی" },
  "نصب": { en: "to erect, hardship, fatigue", ur: "کھڑا کرنا، نصب، تھکاوٹ" },
  "نضج": { en: "to ripen, to be done cooking", ur: "پکنا، پختہ ہونا" },
  "نعق": { en: "to bray, to bleat", ur: "رینکنا، ہانکنا" },
  "نفث": { en: "to blow, to spit", ur: "پھونکنا، تھوکنا" },
  "نفخ": { en: "to blow, to breathe into", ur: "پھونکنا، نفخ" },
  "نفر": { en: "to flee, to avert, to be averse", ur: "بھاگنا، نفرت" },
  "نقب": { en: "to tunnel, to search, chief", ur: "نقب، تلاش، سردار" },
  "نقص": { en: "to decrease, to diminish", ur: "کم کرنا، نقص" },
  "نكر": { en: "to deny, to be unknown, reprehensible", ur: "انکار، نامعلوم، منکر" },
  "نكس": { en: "to turn upside down, to relapse", ur: "الٹنا، پلٹنا" },
  "نمل": { en: "ants, slandering", ur: "چیونٹی، نمل" },
  "نوم": { en: "sleep, slumber", ur: "نیند، سونا" },
  "نيل": { en: "to obtain, to achieve", ur: "پانا، حاصل کرنا" },

  // ─── ه (expanded) ──────────────────────────────────────────────────────────
  "هدم": { en: "to demolish, to destroy", ur: "گرانا، توڑنا" },
  "هدهد": { en: "hoopoe bird", ur: "ہدہد، پرندہ" },
  "هرع": { en: "to rush, to hasten", ur: "دوڑنا، تیز جانا" },
  "هزا": { en: "mockery, to mock, to ridicule", ur: "مذاق اڑانا، ہزل" },
  "هزل": { en: "jest, play, to be weak", ur: "مذاق، ہزل" },
  "همس": { en: "whisper, faint sound", ur: "سرگوشی، آہستہ آواز" },
  "هود": { en: "Jews, to be Jewish, to repent", ur: "یہودی، توبہ" },
  "هون": { en: "ease, gentleness, humiliation", ur: "نرمی، آسانی، ذلت" },
  "هيج": { en: "tumult, to stir up, agitation", ur: "ہنگامہ، اشتعال" },
  "هيم": { en: "to wander, madly in love", ur: "بھٹکنا، دیوانگی" },
  "هرب": { en: "to flee, to escape", ur: "بھاگنا، فرار" },
  "همم": { en: "intention, anxiety, to be about to", ur: "ارادہ، فکر، ہمت" },
  "هنا": { en: "here, now, joy", ur: "یہاں، ابھی" },
  "هبط": { en: "to descend, to go down", ur: "اترنا، نیچے جانا" },

  // ─── و (expanded) ──────────────────────────────────────────────────────────
  "وتر": { en: "odd number, to single out, to deprive", ur: "طاق، اکیلا" },
  "وثق": { en: "trust, reliability, to bind firmly", ur: "اعتماد، ثقہ، باندھنا" },
  "وجل": { en: "fear, to be afraid", ur: "ڈرنا، خوف" },
  "وحد": { en: "oneness, unity, alone", ur: "وحدت، اکیلا، یکتا" },
  "ودد": { en: "love, affection, to love", ur: "محبت، ودادت" },
  "وذر": { en: "to leave, to abandon", ur: "چھوڑنا، ترک کرنا" },
  "ورث": { en: "to inherit, inheritance", ur: "وراثت، وارث" },
  "وري": { en: "to kindle, fire-stick, hidden", ur: "جلانا، پوشیدہ" },
  "وزر": { en: "burden, sin, minister", ur: "بوجھ، وزر، وزیر" },
  "وسط": { en: "middle, center, moderate", ur: "درمیان، وسط، میانہ" },
  "وطي": { en: "to step on, to cohabit", ur: "پیر رکھنا، وطئ" },
  "وعي": { en: "to understand, to contain, consciousness", ur: "سمجھنا، وعی" },
  "وفي": { en: "to fulfil, to be loyal", ur: "وفا کرنا، پورا کرنا" },
  "وقد": { en: "to kindle, to burn", ur: "جلانا، سلگانا" },
  "وقع": { en: "to fall, to occur, to happen", ur: "گرنا، واقع ہونا" },
  "وكل": { en: "to rely upon, to entrust, agent", ur: "توکل، بھروسہ، وکیل" },
  "ولد": { en: "to give birth, child, born", ur: "جننا، بچہ، ولادت" },
  "ونو": { en: "to weaken, fatigue", ur: "کمزور پڑنا، تھکنا" },
  "ويل": { en: "woe, misery", ur: "ویل، ہلاکت، افسوس" },

  // ─── ي (expanded) ──────────────────────────────────────────────────────────
  "يبس": { en: "to dry up, dry, withered", ur: "سوکھنا، خشک" },
  "يتم": { en: "orphan, to be an orphan", ur: "یتیم، بے والدین" },
  "يسا": { en: "to despair, hopelessness", ur: "مایوس ہونا، يأس" },
  "يعس": { en: "to be lucky, to prosper", ur: "خوش نصیب، کامیاب" },
  "يمن": { en: "Yemen, right hand, blessing", ur: "یمن، دایاں، برکت" },
  "ينع": { en: "to ripen, ripe fruit", ur: "پکنا، پختہ" },
  "يقظ": { en: "to be awake, alert, vigilant", ur: "جاگنا، ہوشیار" },
  "يفع": { en: "to reach puberty, to be high", ur: "بالغ ہونا، بلند" },

  // ─── ظ (expanded) ──────────────────────────────────────────────────────────
  "ظعن": { en: "to travel, to move, to depart", ur: "کوچ کرنا، سفر" },
  "ظلل": { en: "shade, shadow, to overshadow", ur: "سایہ، چھایا" },
  "ظمو": { en: "thirst, to be thirsty", ur: "پیاس، پیاسا" },

  // ─── Additional mid-frequency roots ────────────────────────────────────────
  "ادم": { en: "Adam, skin, humanity", ur: "آدم، انسانیت" },
  "اسحق": { en: "Isaac, to laugh", ur: "اسحاق، ہنسنا" },
  "اسماعيل": { en: "Ishmael", ur: "اسماعیل" },
  "ابرهم": { en: "Abraham, father of nations", ur: "ابراہیم، باپ" },
  "اسرئيل": { en: "Israel, servant of God", ur: "اسرائیل" },
  "ثمد": { en: "Thamud, tribe, little water", ur: "ثمود، قوم" },
  "عاد": { en: "ʿĀd, tribe, to return", ur: "عاد، قوم" },
  "لوط": { en: "Lot, to cling, to adhere", ur: "لوط، چمٹنا" },
  "يوسف": { en: "Joseph, to gather", ur: "یوسف" },
  "موسي": { en: "Moses, to save from water", ur: "موسیٰ" },
  "عيسي": { en: "Jesus", ur: "عیسیٰ" },
  "مريم": { en: "Mary", ur: "مریم" },
  "نوح": { en: "Noah, to weep, to lament", ur: "نوح، رونا" },
  "يحيي": { en: "Yahya/John, to live", ur: "یحییٰ" },
  "يعقوب": { en: "Jacob, to follow at heel", ur: "یعقوب" },
  "سليمن": { en: "Solomon, peace", ur: "سلیمان" },
  "داود": { en: "David, beloved", ur: "داؤد" },
  "ادريس": { en: "Idris/Enoch, to study", ur: "ادریس" },
  "سرج": { en: "lamp, torch, sun", ur: "چراغ، سورج، سراج" },
  "رقي": { en: "to rise, to ascend, to charm", ur: "چڑھنا، بلند ہونا" },
  "نبض": { en: "pulse, to throb", ur: "نبض، دھڑکن" },
  "صعب": { en: "difficult, hard", ur: "مشکل، صعب" },
  "قنا": { en: "to be content, to accept", ur: "قناعت، راضی ہونا" },
  "عنب": { en: "grape, vineyard", ur: "انگور، عنب" },
  "رمان": { en: "pomegranate", ur: "انار، رمان" },
  "زيتون": { en: "olive tree, olive", ur: "زیتون" },
  "تين": { en: "fig", ur: "انجیر، تین" },
  "عسل": { en: "honey", ur: "شہد، عسل" },
  "حرير": { en: "silk", ur: "ریشم، حریر" },
  "فضة": { en: "silver", ur: "چاندی، فضہ" },
  "حجارة": { en: "stones", ur: "پتھر، حجارہ" },
  "لجين": { en: "silver, bright water", ur: "چاندی، لجین" },
  "كوثر": { en: "abundance, river in paradise", ur: "کوثر، کثرت" },
  "خلجن": { en: "to agitate, to stir", ur: "ہلانا، جھنجھوڑنا" },
  "قيام": { en: "standing, rising, establishment", ur: "قیام، کھڑا ہونا" },
  "قبلة": { en: "direction of prayer, Kaaba direction", ur: "قبلہ، سمت" },
  "ركز": { en: "to plant firmly, treasure buried", ur: "گاڑنا، خزانہ" },
  "هضم": { en: "to diminish, to wrong", ur: "ہضم کرنا، کم کرنا" },
  "فرج": { en: "to open, private part, relief", ur: "کھولنا، آزاد کرنا، فرج" },
  "سبت": { en: "Sabbath, to rest, to cease", ur: "ہفتہ، آرام، سبت" },
  "كوكب": { en: "star, planet", ur: "ستارہ، کوکب" },
  "بهت": { en: "to be dumbfounded, to lie", ur: "حیران کرنا، بہتان" },
  "درن": { en: "filth, grime", ur: "میل، گندگی" },
  "طمن": { en: "tranquility, to be at ease", ur: "اطمینان، سکون" },
  "كنو": { en: "to name, epithet", ur: "کنیت، لقب" },
  "مشكو": { en: "lantern niche, complaint", ur: "مشکاۃ، شکایت" },
  "بزغ": { en: "to rise (sun), to appear", ur: "طلوع ہونا، نکلنا" },
  "رصد": { en: "to watch, to lie in wait", ur: "نگرانی، گھات" },
  "قصو": { en: "to be extreme, to follow", ur: "انتہا، دور" },
  "كبت": { en: "to humiliate, to frustrate", ur: "ذلیل کرنا، ناکام کرنا" },
  "خذل": { en: "to forsake, to abandon", ur: "چھوڑنا، بے یار و مددگار" },
  "سدر": { en: "lote tree, to be confused", ur: "بیری، حیران" },
  "خمد": { en: "to be extinguished, to die down", ur: "بجھنا، ٹھنڈا پڑنا" },
  "فتي": { en: "young man, youth", ur: "جوان، نوجوان" },
  "سدو": { en: "to hang loose, to let down", ur: "لٹکانا، ڈھیلا چھوڑنا" },
  "جلد": { en: "skin, flogging, to flog", ur: "چمڑا، کوڑے مارنا، جلد" },
  "عمي": { en: "blindness, to be blind", ur: "اندھا، عمیٰ، نابینا" },
  "صمم": { en: "deafness, to be deaf", ur: "بہرا، صمم" },
  "ختل": { en: "deceit, to beguile", ur: "دھوکہ، فریب" },
  "وسو": { en: "whispering, to whisper", ur: "وسوسہ، پھسپھسانا" },
  "رمض": { en: "intense heat, Ramadan", ur: "سخت گرمی، رمضان" },
  "جبل": { en: "mountain, to be innate", ur: "پہاڑ، جبل" },
  "بحر": { en: "sea, ocean", ur: "سمندر، بحر" },
  "غيث": { en: "rain, relief", ur: "بارش، فریاد" },
  "صيب": { en: "rain, pouring", ur: "موسلا دھار بارش" },
  "ودق": { en: "rain, lightning", ur: "بارش، چمک" },
  "حبك": { en: "firmly woven, tracks of sky", ur: "مضبوطی سے بنا، راستے" },
  "سحاب": { en: "clouds", ur: "بادل، سحاب" },
  "فلك": { en: "orbits, celestial sphere, ship", ur: "کہکشاں، کشتی، فلک" },
  "ريح": { en: "wind, breath, spirit", ur: "ہوا، ریح" },
  "مطر": { en: "rain, to rain", ur: "بارش، مطر" },
  "مقت": { en: "hatred, loathing, abomination", ur: "نفرت، غصہ، مقت" },
  "نبر": { en: "to raise, elevation, to speak", ur: "اٹھانا، بلندی" },
  "فقد": { en: "loss, to be missing, to lack", ur: "گم ہونا، کھونا" },
  "غرس": { en: "to plant, plantation", ur: "لگانا، کاشت" },
  "خضر": { en: "green, Khidr (the green one)", ur: "سبز، خضر" },
  "حصد": { en: "harvest, to reap", ur: "فصل کاٹنا، حصاد" },
  "نخل": { en: "palm tree, date palm", ur: "کھجور کا درخت" },
  "سنبل": { en: "ear of grain, spike", ur: "بالی، سنبل" },
  "حب": { en: "grain, seed, love", ur: "دانہ، محبت، حب" },
  "درر": { en: "pearls, to pour", ur: "موتی، بہانا" },
  "لؤلؤ": { en: "pearls", ur: "موتی، لؤلؤ" },
  "مرجن": { en: "coral, small pearls", ur: "مرجان، مونگا" },
  "عبقر": { en: "fine cloth, carpet", ur: "عبقری، قالین" },
  "حندس": { en: "intense darkness", ur: "گہرا اندھیرا" },
  "خسر": { en: "loss, ruin, to lose", ur: "خسارہ، نقصان" },
  "وبل": { en: "heavy rain, ill consequence", ur: "موسلا دھار، برا انجام" },
  "طفل": { en: "child, infant, to be gentle", ur: "بچہ، طفل" },
  "رضع": { en: "to suckle, nursing", ur: "دودھ پلانا، رضاعت" },
  "طلق": { en: "divorce, to free, to give birth", ur: "طلاق، آزاد کرنا" },
  "نفل": { en: "voluntary deed, spoils of war", ur: "نفل، عطا" },
  "جزل": { en: "generous, to split", ur: "سخی، کاٹنا" },
  "ذرو": { en: "to scatter, to spread", ur: "بکھیرنا، پھیلانا" },
  "حبن": { en: "to guard, belly", ur: "حفاظت، پیٹ" },
  "شبع": { en: "to be satisfied, full", ur: "پیٹ بھرنا، سیر ہونا" },
  "جشن": { en: "body, belly", ur: "جسم، پیٹ" },
};

/**
 * Synchronous lookup — no network required.
 *
 * The input root is normalized before lookup, so raw QAC root strings
 * (which already use the canonical form) are matched correctly, as are
 * any alternate alif/ya forms passed by callers.
 *
 * Returns null when the root is not in the curated table.
 */
export function lookupRootMeaning(root: string | null | undefined): RootMeaning | null {
  if (!root) return null;
  const key = normalize(root);
  return ROOT_MEANINGS[key] ?? null;
}
