export interface Surah {
  number: number;
  arabicName: string;
  name: string;
  englishName: string;
  verses: number;
  type: "Meccan" | "Medinan";
  page: number;
}

export const surahs: Surah[] = [
  { number: 1,   arabicName: "الْفَاتِحَة",    name: "Al-Fatihah",     englishName: "The Opening",           verses: 7,   type: "Meccan",  page: 1   },
  { number: 2,   arabicName: "الْبَقَرَة",      name: "Al-Baqarah",     englishName: "The Cow",               verses: 286, type: "Medinan", page: 2   },
  { number: 3,   arabicName: "آلِ عِمْرَان",    name: "Ali 'Imran",     englishName: "Family of Imran",       verses: 200, type: "Medinan", page: 50  },
  { number: 4,   arabicName: "النِّسَاء",       name: "An-Nisa",        englishName: "The Women",             verses: 176, type: "Medinan", page: 77  },
  { number: 5,   arabicName: "الْمَائِدَة",     name: "Al-Ma'idah",     englishName: "The Table Spread",      verses: 120, type: "Medinan", page: 106 },
  { number: 6,   arabicName: "الْأَنْعَام",     name: "Al-An'am",       englishName: "The Cattle",            verses: 165, type: "Meccan",  page: 128 },
  { number: 7,   arabicName: "الْأَعْرَاف",     name: "Al-A'raf",       englishName: "The Heights",           verses: 206, type: "Meccan",  page: 151 },
  { number: 8,   arabicName: "الْأَنْفَال",     name: "Al-Anfal",       englishName: "The Spoils of War",     verses: 75,  type: "Medinan", page: 177 },
  { number: 9,   arabicName: "التَّوْبَة",      name: "At-Tawbah",      englishName: "The Repentance",        verses: 129, type: "Medinan", page: 187 },
  { number: 10,  arabicName: "يُونُس",          name: "Yunus",          englishName: "Jonah",                 verses: 109, type: "Meccan",  page: 208 },
  { number: 11,  arabicName: "هُود",            name: "Hud",            englishName: "Hud",                   verses: 123, type: "Meccan",  page: 221 },
  { number: 12,  arabicName: "يُوسُف",          name: "Yusuf",          englishName: "Joseph",                verses: 111, type: "Meccan",  page: 235 },
  { number: 13,  arabicName: "الرَّعْد",        name: "Ar-Ra'd",        englishName: "The Thunder",           verses: 43,  type: "Medinan", page: 249 },
  { number: 14,  arabicName: "إِبْرَاهِيم",    name: "Ibrahim",        englishName: "Abraham",               verses: 52,  type: "Meccan",  page: 255 },
  { number: 15,  arabicName: "الْحِجْر",        name: "Al-Hijr",        englishName: "The Rocky Tract",       verses: 99,  type: "Meccan",  page: 262 },
  { number: 16,  arabicName: "النَّحْل",        name: "An-Nahl",        englishName: "The Bee",               verses: 128, type: "Meccan",  page: 267 },
  { number: 17,  arabicName: "الْإِسْرَاء",    name: "Al-Isra",        englishName: "The Night Journey",     verses: 111, type: "Meccan",  page: 282 },
  { number: 18,  arabicName: "الْكَهْف",        name: "Al-Kahf",        englishName: "The Cave",              verses: 110, type: "Meccan",  page: 293 },
  { number: 19,  arabicName: "مَرْيَم",         name: "Maryam",         englishName: "Mary",                  verses: 98,  type: "Meccan",  page: 305 },
  { number: 20,  arabicName: "طه",              name: "Ta-Ha",          englishName: "Ta-Ha",                 verses: 135, type: "Meccan",  page: 312 },
  { number: 21,  arabicName: "الْأَنبِيَاء",   name: "Al-Anbiya",      englishName: "The Prophets",          verses: 112, type: "Meccan",  page: 322 },
  { number: 22,  arabicName: "الْحَجّ",         name: "Al-Hajj",        englishName: "The Pilgrimage",        verses: 78,  type: "Medinan", page: 332 },
  { number: 23,  arabicName: "الْمُؤْمِنُون",  name: "Al-Mu'minun",    englishName: "The Believers",         verses: 118, type: "Meccan",  page: 342 },
  { number: 24,  arabicName: "النُّور",         name: "An-Nur",         englishName: "The Light",             verses: 64,  type: "Medinan", page: 350 },
  { number: 25,  arabicName: "الْفُرْقَان",    name: "Al-Furqan",      englishName: "The Criterion",         verses: 77,  type: "Meccan",  page: 359 },
  { number: 26,  arabicName: "الشُّعَرَاء",    name: "Ash-Shu'ara",    englishName: "The Poets",             verses: 227, type: "Meccan",  page: 367 },
  { number: 27,  arabicName: "النَّمْل",        name: "An-Naml",        englishName: "The Ant",               verses: 93,  type: "Meccan",  page: 377 },
  { number: 28,  arabicName: "الْقَصَص",        name: "Al-Qasas",       englishName: "The Stories",           verses: 88,  type: "Meccan",  page: 385 },
  { number: 29,  arabicName: "الْعَنكَبُوت",   name: "Al-Ankabut",     englishName: "The Spider",            verses: 69,  type: "Meccan",  page: 396 },
  { number: 30,  arabicName: "الرُّوم",         name: "Ar-Rum",         englishName: "The Romans",            verses: 60,  type: "Meccan",  page: 404 },
  { number: 31,  arabicName: "لُقْمَان",        name: "Luqman",         englishName: "Luqman",                verses: 34,  type: "Meccan",  page: 411 },
  { number: 32,  arabicName: "السَّجْدَة",      name: "As-Sajdah",      englishName: "The Prostration",       verses: 30,  type: "Meccan",  page: 415 },
  { number: 33,  arabicName: "الْأَحْزَاب",    name: "Al-Ahzab",       englishName: "The Combined Forces",   verses: 73,  type: "Medinan", page: 418 },
  { number: 34,  arabicName: "سَبَأ",           name: "Saba",           englishName: "Sheba",                 verses: 54,  type: "Meccan",  page: 428 },
  { number: 35,  arabicName: "فَاطِر",          name: "Fatir",          englishName: "The Originator",        verses: 45,  type: "Meccan",  page: 434 },
  { number: 36,  arabicName: "يس",              name: "Ya-Sin",         englishName: "Ya-Sin",                verses: 83,  type: "Meccan",  page: 440 },
  { number: 37,  arabicName: "الصَّافَّات",    name: "As-Saffat",      englishName: "Those Lined Up",        verses: 182, type: "Meccan",  page: 446 },
  { number: 38,  arabicName: "ص",               name: "Sad",            englishName: "Sad",                   verses: 88,  type: "Meccan",  page: 453 },
  { number: 39,  arabicName: "الزُّمَر",        name: "Az-Zumar",       englishName: "The Groups",            verses: 75,  type: "Meccan",  page: 458 },
  { number: 40,  arabicName: "غَافِر",          name: "Ghafir",         englishName: "The Forgiver",          verses: 85,  type: "Meccan",  page: 467 },
  { number: 41,  arabicName: "فُصِّلَت",        name: "Fussilat",       englishName: "Explained in Detail",   verses: 54,  type: "Meccan",  page: 477 },
  { number: 42,  arabicName: "الشُّورَى",       name: "Ash-Shura",      englishName: "The Consultation",      verses: 53,  type: "Meccan",  page: 483 },
  { number: 43,  arabicName: "الزُّخْرُف",     name: "Az-Zukhruf",     englishName: "The Gold Adornment",    verses: 89,  type: "Meccan",  page: 489 },
  { number: 44,  arabicName: "الدُّخَان",       name: "Ad-Dukhan",      englishName: "The Smoke",             verses: 59,  type: "Meccan",  page: 496 },
  { number: 45,  arabicName: "الْجَاثِيَة",    name: "Al-Jathiyah",    englishName: "The Crouching",         verses: 37,  type: "Meccan",  page: 499 },
  { number: 46,  arabicName: "الْأَحْقَاف",    name: "Al-Ahqaf",       englishName: "The Wind-Curved Dunes", verses: 35,  type: "Meccan",  page: 502 },
  { number: 47,  arabicName: "مُحَمَّد",        name: "Muhammad",       englishName: "Muhammad",              verses: 38,  type: "Medinan", page: 507 },
  { number: 48,  arabicName: "الْفَتْح",        name: "Al-Fath",        englishName: "The Victory",           verses: 29,  type: "Medinan", page: 511 },
  { number: 49,  arabicName: "الْحُجُرَات",    name: "Al-Hujurat",     englishName: "The Rooms",             verses: 18,  type: "Medinan", page: 515 },
  { number: 50,  arabicName: "ق",               name: "Qaf",            englishName: "Qaf",                   verses: 45,  type: "Meccan",  page: 518 },
  { number: 51,  arabicName: "الذَّارِيَات",   name: "Adh-Dhariyat",   englishName: "The Winnowing Winds",   verses: 60,  type: "Meccan",  page: 520 },
  { number: 52,  arabicName: "الطُّور",         name: "At-Tur",         englishName: "The Mount",             verses: 49,  type: "Meccan",  page: 523 },
  { number: 53,  arabicName: "النَّجْم",        name: "An-Najm",        englishName: "The Star",              verses: 62,  type: "Meccan",  page: 526 },
  { number: 54,  arabicName: "الْقَمَر",        name: "Al-Qamar",       englishName: "The Moon",              verses: 55,  type: "Meccan",  page: 528 },
  { number: 55,  arabicName: "الرَّحْمَن",      name: "Ar-Rahman",      englishName: "The Beneficent",        verses: 78,  type: "Medinan", page: 531 },
  { number: 56,  arabicName: "الْوَاقِعَة",    name: "Al-Waqi'ah",     englishName: "The Inevitable",        verses: 96,  type: "Meccan",  page: 534 },
  { number: 57,  arabicName: "الْحَدِيد",       name: "Al-Hadid",       englishName: "The Iron",              verses: 29,  type: "Medinan", page: 537 },
  { number: 58,  arabicName: "الْمُجَادِلَة",  name: "Al-Mujadila",    englishName: "The Pleading Woman",    verses: 22,  type: "Medinan", page: 542 },
  { number: 59,  arabicName: "الْحَشْر",        name: "Al-Hashr",       englishName: "The Exile",             verses: 24,  type: "Medinan", page: 545 },
  { number: 60,  arabicName: "الْمُمْتَحَنَة", name: "Al-Mumtahanah",  englishName: "She That Is Examined",  verses: 13,  type: "Medinan", page: 549 },
  { number: 61,  arabicName: "الصَّف",          name: "As-Saf",         englishName: "The Ranks",             verses: 14,  type: "Medinan", page: 551 },
  { number: 62,  arabicName: "الْجُمُعَة",     name: "Al-Jumu'ah",     englishName: "Friday",                verses: 11,  type: "Medinan", page: 553 },
  { number: 63,  arabicName: "الْمُنَافِقُون", name: "Al-Munafiqun",   englishName: "The Hypocrites",        verses: 11,  type: "Medinan", page: 554 },
  { number: 64,  arabicName: "التَّغَابُن",    name: "At-Taghabun",    englishName: "The Mutual Disillusion", verses: 18, type: "Medinan", page: 556 },
  { number: 65,  arabicName: "الطَّلَاق",      name: "At-Talaq",       englishName: "The Divorce",           verses: 12,  type: "Medinan", page: 558 },
  { number: 66,  arabicName: "التَّحْرِيم",    name: "At-Tahrim",      englishName: "The Prohibiting",       verses: 12,  type: "Medinan", page: 560 },
  { number: 67,  arabicName: "الْمُلْك",        name: "Al-Mulk",        englishName: "The Sovereignty",       verses: 30,  type: "Meccan",  page: 562 },
  { number: 68,  arabicName: "الْقَلَم",        name: "Al-Qalam",       englishName: "The Pen",               verses: 52,  type: "Meccan",  page: 564 },
  { number: 69,  arabicName: "الْحَاقَّة",     name: "Al-Haqqah",      englishName: "The Reality",           verses: 52,  type: "Meccan",  page: 566 },
  { number: 70,  arabicName: "الْمَعَارِج",    name: "Al-Ma'arij",     englishName: "The Ascending Stairways", verses: 44, type: "Meccan", page: 568 },
  { number: 71,  arabicName: "نُوح",            name: "Nuh",            englishName: "Noah",                  verses: 28,  type: "Meccan",  page: 570 },
  { number: 72,  arabicName: "الْجِن",          name: "Al-Jinn",        englishName: "The Jinn",              verses: 28,  type: "Meccan",  page: 572 },
  { number: 73,  arabicName: "الْمُزَّمِّل",   name: "Al-Muzzammil",   englishName: "The Enshrouded One",    verses: 20,  type: "Meccan",  page: 574 },
  { number: 74,  arabicName: "الْمُدَّثِّر",   name: "Al-Muddaththir", englishName: "The Cloaked One",       verses: 56,  type: "Meccan",  page: 575 },
  { number: 75,  arabicName: "الْقِيَامَة",    name: "Al-Qiyamah",     englishName: "The Resurrection",      verses: 40,  type: "Meccan",  page: 577 },
  { number: 76,  arabicName: "الْإِنسَان",     name: "Al-Insan",       englishName: "The Man",               verses: 31,  type: "Medinan", page: 578 },
  { number: 77,  arabicName: "الْمُرْسَلَات",  name: "Al-Mursalat",    englishName: "The Emissaries",        verses: 50,  type: "Meccan",  page: 580 },
  { number: 78,  arabicName: "النَّبَأ",        name: "An-Naba",        englishName: "The Tidings",           verses: 40,  type: "Meccan",  page: 582 },
  { number: 79,  arabicName: "النَّازِعَات",   name: "An-Nazi'at",     englishName: "Those Who Drag Forth",  verses: 46,  type: "Meccan",  page: 583 },
  { number: 80,  arabicName: "عَبَسَ",          name: "Abasa",          englishName: "He Frowned",            verses: 42,  type: "Meccan",  page: 585 },
  { number: 81,  arabicName: "التَّكْوِير",    name: "At-Takwir",      englishName: "The Overthrowing",      verses: 29,  type: "Meccan",  page: 586 },
  { number: 82,  arabicName: "الِانفِطَار",    name: "Al-Infitar",     englishName: "The Cleaving",          verses: 19,  type: "Meccan",  page: 587 },
  { number: 83,  arabicName: "الْمُطَفِّفِين", name: "Al-Mutaffifin",  englishName: "The Defrauding",        verses: 36,  type: "Meccan",  page: 587 },
  { number: 84,  arabicName: "الِانشِقَاق",    name: "Al-Inshiqaq",    englishName: "The Sundering",         verses: 25,  type: "Meccan",  page: 589 },
  { number: 85,  arabicName: "الْبُرُوج",       name: "Al-Buruj",       englishName: "The Mansions of Stars", verses: 22,  type: "Meccan",  page: 590 },
  { number: 86,  arabicName: "الطَّارِق",       name: "At-Tariq",       englishName: "The Nightcomer",        verses: 17,  type: "Meccan",  page: 591 },
  { number: 87,  arabicName: "الْأَعْلَى",      name: "Al-A'la",        englishName: "The Most High",         verses: 19,  type: "Meccan",  page: 591 },
  { number: 88,  arabicName: "الْغَاشِيَة",    name: "Al-Ghashiyah",   englishName: "The Overwhelming",      verses: 26,  type: "Meccan",  page: 592 },
  { number: 89,  arabicName: "الْفَجْر",        name: "Al-Fajr",        englishName: "The Dawn",              verses: 30,  type: "Meccan",  page: 593 },
  { number: 90,  arabicName: "الْبَلَد",        name: "Al-Balad",       englishName: "The City",              verses: 20,  type: "Meccan",  page: 594 },
  { number: 91,  arabicName: "الشَّمْس",        name: "Ash-Shams",      englishName: "The Sun",               verses: 15,  type: "Meccan",  page: 595 },
  { number: 92,  arabicName: "اللَّيْل",        name: "Al-Layl",        englishName: "The Night",             verses: 21,  type: "Meccan",  page: 595 },
  { number: 93,  arabicName: "الضُّحَى",        name: "Ad-Duha",        englishName: "The Morning Hours",     verses: 11,  type: "Meccan",  page: 596 },
  { number: 94,  arabicName: "الشَّرْح",        name: "Ash-Sharh",      englishName: "The Relief",            verses: 8,   type: "Meccan",  page: 596 },
  { number: 95,  arabicName: "التِّين",         name: "At-Tin",         englishName: "The Fig",               verses: 8,   type: "Meccan",  page: 597 },
  { number: 96,  arabicName: "الْعَلَق",        name: "Al-Alaq",        englishName: "The Clot",              verses: 19,  type: "Meccan",  page: 597 },
  { number: 97,  arabicName: "الْقَدْر",        name: "Al-Qadr",        englishName: "The Power",             verses: 5,   type: "Meccan",  page: 598 },
  { number: 98,  arabicName: "الْبَيِّنَة",    name: "Al-Bayyinah",    englishName: "The Clear Proof",       verses: 8,   type: "Medinan", page: 598 },
  { number: 99,  arabicName: "الزَّلْزَلَة",   name: "Az-Zalzalah",    englishName: "The Earthquake",        verses: 8,   type: "Medinan", page: 599 },
  { number: 100, arabicName: "الْعَادِيَات",   name: "Al-Adiyat",      englishName: "The Courser",           verses: 11,  type: "Meccan",  page: 599 },
  { number: 101, arabicName: "الْقَارِعَة",    name: "Al-Qari'ah",     englishName: "The Calamity",          verses: 11,  type: "Meccan",  page: 600 },
  { number: 102, arabicName: "التَّكَاثُر",    name: "At-Takathur",    englishName: "The Rivalry in World Increase", verses: 8, type: "Meccan", page: 600 },
  { number: 103, arabicName: "الْعَصْر",        name: "Al-Asr",         englishName: "The Declining Day",     verses: 3,   type: "Meccan",  page: 601 },
  { number: 104, arabicName: "الْهُمَزَة",      name: "Al-Humazah",     englishName: "The Traducer",          verses: 9,   type: "Meccan",  page: 601 },
  { number: 105, arabicName: "الْفِيل",         name: "Al-Fil",         englishName: "The Elephant",          verses: 5,   type: "Meccan",  page: 601 },
  { number: 106, arabicName: "قُرَيْش",         name: "Quraysh",        englishName: "Quraysh",               verses: 4,   type: "Meccan",  page: 602 },
  { number: 107, arabicName: "الْمَاعُون",      name: "Al-Ma'un",       englishName: "The Small Kindnesses",  verses: 7,   type: "Meccan",  page: 602 },
  { number: 108, arabicName: "الْكَوْثَر",      name: "Al-Kawthar",     englishName: "The Abundance",         verses: 3,   type: "Meccan",  page: 602 },
  { number: 109, arabicName: "الْكَافِرُون",   name: "Al-Kafirun",     englishName: "The Disbelievers",      verses: 6,   type: "Meccan",  page: 603 },
  { number: 110, arabicName: "النَّصْر",        name: "An-Nasr",        englishName: "The Divine Support",    verses: 3,   type: "Medinan", page: 603 },
  { number: 111, arabicName: "الْمَسَد",        name: "Al-Masad",       englishName: "The Palm Fibre",        verses: 5,   type: "Meccan",  page: 603 },
  { number: 112, arabicName: "الْإِخْلَاص",    name: "Al-Ikhlas",      englishName: "The Sincerity",         verses: 4,   type: "Meccan",  page: 604 },
  { number: 113, arabicName: "الْفَلَق",        name: "Al-Falaq",       englishName: "The Daybreak",          verses: 5,   type: "Meccan",  page: 604 },
  { number: 114, arabicName: "النَّاس",         name: "An-Nas",         englishName: "The Mankind",           verses: 6,   type: "Meccan",  page: 604 },
];
